### ISSUE TITLE
Re: Parallax

### ISSUE THREAD

**Issue by Trinab** [wagerfield/parallax#100]
Hi, 

I really like your parallax. It worked really well in a project I was working on before.

However this time I was wondering if you can help me....

I have been trying to use your parallax code which works brilliantly on the smaller images but when I set it to full screen, the corner images move in and it looks all off (see attached image) You can see that the layers look cut off. No matter how big I make them it the sharp edge can still be seen. Is there something that I am doing wrong? Have you seen this happen before?

Looking forward to hearing from you,
Trina

**Comment by RRorg** [comment]
´
