### ISSUE TITLE
Double body tags in Rails app

### ISSUE THREAD

**Issue by harisaurus** [wagerfield/parallax#113]
Including the parallax.js file (vanilla or jQuery) results in two body tags being rendered. This, obviously, causes a lot of issues.

![metricsmark](https://cloud.githubusercontent.com/assets/6800875/5349846/1bd3ea6a-7f0b-11e4-833d-eae6dc9ebf2c.png)

Any solutions or bugfixes most welcome!

**Comment by tutuca** [comment]
I have the same issue without using rails. 
I concatenate the files into a single script, so including parallax at the bottom is not a viable option. 

Pity, this is the nicer parallax lib of the bunch.

**Comment by totty90** [comment]
+1

**Comment by Andrew-Dyachenko** [comment]
I have been moved ```javascript <script src="/bower_components/parallax/deploy/jquery.parallax.min.js"></script> ``` after to the bottom (after footer) too. It helps! But it looks like something wrong...

**Comment by danielfriis** [comment]
I'm having the same issue. Moving the script to the bottom didn't work. The problem seems to be with Turbolinks. Removing Turbolinks from the app fixes the issue.

**Comment by mlbileschi** [comment]
You can also wrap it in a document ready call, and that seems to fix the issue for me.

**Comment by RRorg** [comment]
this should be fixed in the latest master branch
