### ISSUE TITLE
Can this be used on a series of DIVs instead of LIs in a UL?

### ISSUE THREAD

**Issue by JAAulde** [wagerfield/parallax#116]
Greetings,

I was wondering if the parallax plugin required a `UL` containing `LI.layer` elements, or could it be run on a `DIV` which contained `DIV.layer` elements?

Thanks,
Jim

**Comment by ivansulimenko** [comment]
+1

**Comment by ivansulimenko** [comment]
also how to make it with inline elements? is it possible?

**Comment by dt1973** [comment]
Please set up a test case and we'll take it from there:

http://css-tricks.com/reduced-test-cases/

**Comment by MuTLY** [comment]
@JAAulde yes, you can do just that.

Check this http://codepen.io/MuTLY/pen/dPagbP

**Comment by JAAulde** [comment]
Excellent, thanks! I'll pass this along for the UI guy to compare to his own work.

**Comment by kgilmur** [comment]
Seems to disable my page from scrolling...how can i keep the parallax but still allow scrolling?

**Comment by fullofcaffeine** [comment]
+1
