### ISSUE TITLE
3D tilting for wordpress

### ISSUE THREAD

**Issue by jonybigude** [wagerfield/parallax#120]
Sorry if this is the wrong place to ask this but I have googled all morning and I am out of options now.

I can surely find a lot of wordpress themes with parallax scrolling backgrounds and image sliders but that is not what I want, what I want is what is presented at the official Parallax web page (http://matthew.wagerfield.com/parallax/).

How could I achieve that on Wordpress? Or, does anyone knows of a WP theme with that?

Many thanks in advance!

**Comment by RRorg** [comment]
Parallax.js is backend-agnostic, so you'll need to be more precise in describing your problem with implementing it. What did you try so far, what doesn't work? Please reopen this issue if problems persist.

**Comment by thedonquixotic** [comment]
Just leaving a note here. I'm planning on implementing this in Wordpress. I'll update here with how it goes for people who might find this issue someday in the future. So far, looking at the structure of the HTML, it looks like it should be fairly easy to do.
