### ISSUE TITLE
iOS Rotation 'Bug' with navbar

### ISSUE THREAD

**Issue by eloisemonteiro** [wagerfield/parallax#124]
Hi, i'm using parallax.js with a navbar fixed on top but when I use the rotation to force to see my page on landscape mode it has some sort of realignment of the width and my navbar stays in the portrait width, here's a picture to better understand.  

![erro](https://cloud.githubusercontent.com/assets/8793011/7207631/438a1360-e511-11e4-9dac-b372c7fa2bbe.png)

**Comment by RRorg** [comment]
This seems to be a problem with your implementation of the navbar and not the library. Please reopen this issue and provide a working demo if problems persist.
