### ISSUE TITLE
Incorrect work with Samsung Galaxy Tab

### ISSUE THREAD

**Issue by mydylan** [wagerfield/parallax#126]
Hi. 
I found that this script incorrect work with tablet where default orientation is landscape(Samsung Galaxy Tab 2 for example), and therefore this devices have not the same axis like device where default orientation is portrait(iPad, Nexus). I`m trying to find a solution, but with no effect. The problem is how to know what the orientation of device is default or something like that. 

Any idea?

**Comment by RRorg** [comment]
I'll be closing this issue since it's over a year old and nobody else has chimed in. As I don't own a Samsung Tablet, I can't test this myself :( please feel free to reopen this issue if you have additional info!
