### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by JoshuaNovak919** [wagerfield/parallax#128]
Is there a newer fork or version of this somewhere? This version hasn't been updated in a year, and github can't load the forks graph since there are so many. Preferably one with some speed enhancements.

**Comment by pascalwacker** [comment]
@JoshuaNovak919 let me know, if you find one (specially that works with ios devices!)

**Comment by RRorg** [comment]
Good news, everybody: we're trying to get this project back up to speed again! Please check out the latest master branch version and let me know if performance and iOS support are to your likings now :)
