### ISSUE TITLE
How disable set to body style overflow:hidden?

### ISSUE THREAD

**Issue by nkl90** [wagerfield/parallax#129]
Hello, sorry for my English, I am a Russian. How I can disable set style to body "overflow:hidden"? Now I'm doing it so
$(function(){
    $('#scene').parallax();
    $('body').attr('style', '');
});
But i fing this is bad practice. Maybe I missed something in the documentation says how it's done by a native method?

**Comment by asleepwalker** [comment]
Try to just move the script tag to the bottom of body element. It will resolve your issue.

**Comment by nkl90** [comment]
Thanks for the answer, but I have solved this problem. Then I just commented out this line https://github.com/wagerfield/parallax/blob/master/source/jquery.parallax.js#L149
