### ISSUE TITLE
Pause while resizing.

### ISSUE THREAD

**Issue by markoradak** [wagerfield/parallax#136]
Nothing to major, but I think it would improove overall feel if the function pauses while browser is being resized. At the moment, it looks a bit heavy if you try resizing your browser while function is running normally.

Cheers,
Marko

**Comment by RRorg** [comment]
As it stands, there is no event that gets triggered on resizing-end. It could be faked, in a dirty hack-ish way, by using timeouts, but let's rather not do that.
