### ISSUE TITLE
Background image not re-sizing with window

### ISSUE THREAD

**Issue by SilvanTheuma** [wagerfield/parallax#137]
Hi,

I have just applied this to my website, the parallax works fine however the background image is not covering the whole window when resizing it. Can anyone help me pls.

This is my website www.silvantheuma.com

Thanks

**Comment by anthony-dandrea** [comment]
@SilvanTheuma add this css to your `.background` class
```
.background {
  ...
  background-position: center center;
  background-size: cover;
}
```
