### ISSUE TITLE
It's not working in safari 

### ISSUE THREAD

**Issue by prncdahal** [wagerfield/parallax#139]
http://ortea.e-commerce-hongkong.com/hong_kong/profile

**Comment by wagerfield** [comment]
Can't see where parallax is used on this site, so I'm assuming that you abandoned it?

If I'm missing something and you are still experiencing issues in Safari, please could you elaborate on your problem because from what I'm seeing, parallax works fine in Safari.

**Comment by prncdahal** [comment]
Hello *Matthew*
Safari Issue has been fixed. Thanks for the response 😀.
Regards Ramesh Dahal


On Tue, Feb 9, 2016 at 7:06 PM, Matthew Wagerfield <notifications@github.com
