### ISSUE TITLE
Global parallax effect

### ISSUE THREAD

**Issue by fraserYT** [wagerfield/parallax#140]
I was previously using the parallax implementation in jkit, but have switched to this plugin because it's smoother and works with the accelerometer on mobile devices. The one feature I miss from there though, or can't find at least, is the ability to set the parallax effect to follow the cursor globally or locally.

So, if it is set to work globally, and I have a parallax image which doesn't fill the screen, the effect will work as the cursor moves across the entire width and height of the screen, even if it is outside the parallax image itself.

Is this something that is easily possible with parallax.js?

**Comment by RRorg** [comment]
Currently it's always globally, but optional support for local-only detection is planned, as discussed in #85
