### ISSUE TITLE
Delay the parallax response

### ISSUE THREAD

**Issue by Gespinha** [wagerfield/parallax#141]
Hi there,

I've been playing around with this parallax plugin and was wondering, how can you assign a larger ease to the parallax when the user's cursor changes direction?

As you can see, in the parallax used in gv.com, it actually is really slow and smooth when the user changes direction. Not like here, where it changes almost instantly.

Can you please help me on achieving this?

Thanks in advance

**Comment by RRorg** [comment]
This is a good idea and I'll see what I can do about it!

**Comment by RRorg** [comment]
sorry, I mis-read your question, this is already possible. Use the `friction()` method or the `frictionX` & `frictionY` parameters
