### ISSUE TITLE
Continued Development

### ISSUE THREAD

**Issue by pixeltherapy** [wagerfield/parallax#144]
Ever grateful to Matthew Wagerfield & Claudio Guglieri for putting this together, although with the apparent popularity of this repo on github and it's (nail-biting) use in production means that some continued development of the project is very much needed.

If anyone is willing to serve this goal then post here to co-ordinate the effort, stating your contribution, linking to valid forks or any other way you can forward this endeavour.

Myself, I am a front-end designer wth a focus on SVG & JS animation so I'm more use as a feature scope, feature debug, demo and docs kinda contributor ;o) Though I would be happy to host any new repo and take the lead in that regard.

This thread is intended to serve as a signpost for others looking to answer the same question so bump away, even if my call falls on deaf ears!

**Comment by dt1973** [comment]
We have tried reaching Matthew on multiple occasions but he's ignored us every time. If you're serious about this, track down his telephone number in London and give him a call.

**Comment by pixeltherapy** [comment]
Roger! :o)

**Comment by rafaelnco** [comment]
> Though I would be happy to host any new repo and take the lead in that regard.

@pixeltherapy if this is the case, please, notify me as I could contribute in so many ways!

**Comment by dt1973** [comment]
:+1:

**Comment by joelcdoyle** [comment]
Love this repo. Would love to see continued development. :+1:

**Comment by wagerfield** [comment]
Hi Guys,

Sorry for painful the lack of response to the issues and comments on this repo. I've been incredibly busy with a product I'm working on, so have not had the time to maintain parallax.

I'll go through the issues over the coming week, but it would be super helpful if someone could consolidate any feedback, ideas etc. that the community has been asking for and post them here.

Thanks,

Matt

**Comment by SplitCoreGaming** [comment]
So glad you are back! I have been butchering my install with fixes/changes to the point I broke most things. Many thanks for supporting development.

**Comment by rafaelnco** [comment]
Hey @wagerfield, glad you're back!

I guess there's a lot to be done here but the community is here to help! I've got some ideas for parallax.js but [this one](https://github.com/wagerfield/parallax/issues/145) seems to be the most important for me. Although we've shared many greater ideas, I would really appreciate to read your opinion about this (e.g. if this is possible).

Also, there's a [pull request](https://github.com/wagerfield/parallax/pull/92) about performance that you must find just interesting as [this one](https://github.com/wagerfield/parallax/pull/118), that suggests a **new version release**.

Take your time, we've been waiting for this!

att, Rafael

**Comment by tony99nyr** [comment]
He's dead, Jim.

**Comment by RRorg** [comment]
While I wish @wagerfield would give the repo to someone with a bit more time, you can't really blame him for not wanting to give up a +10,000⭑ repo 😉 
I'll see what I can do about this in the coming days, would be more than willing to create a fork and incorporate some of the great pull requests that are open, as well as handling the open issues.

**Comment by RRorg** [comment]
Hey friends, I'm now a collaborator for this repo and will try to get my hands dirty. If you have any urgent problems, feel free to directly tag me on Github or send me an E-Mail!
