### ISSUE TITLE
[idea] Runtime re-calibration

### ISSUE THREAD

**Issue by rafaelnco** [wagerfield/parallax#145]
_So many uncommented Issues, but let me register this anyway_
### Problem

In **mobile devices**, _when using gyroscope or motion detection hardware_, the user is free to **move around while still carrying the device**. This causes a strange behaviour in which the elements float around like crazy because the user is holding the device in such a different way than that checked in **the first (and only?) calibration step**.
### Solution

So the first thing I've thought of was to re-calibrate Parallax at runtime. This would happen after checking for one or some of the following behaviours:
- abrupt change in `orientation` (gyroscope/motion detection hardware)
- `elements` are outside a given `hitbox` (given parameter at initialization)
- `viewport` (your "window" to parallax layers) is outside a given `safe viewport` (given parameter at initialization)
### Implementation

As you see, a solution can easily be implemented regarding the webdesigner knowledge about whether the user is pointing his device in expected ways (e.g looking at content that really matters v.s. exploring the surroundings and limits of the parallax layers).

Considering that viewports are going to be used to solve this problem, you can check some images which can explain it way better than my words:
#### So, if you're pointing your device to another viewport, recalibrate Parallax!

![3d](http://i.stack.imgur.com/HGvlv.png)
#### That would be the two dimensional viewport map:

![2d](http://gwydir.demon.co.uk/jo/solid/buckynet.gif)
#### There can be so many (or not) points of recalibration:

![many options](https://upload.wikimedia.org/wikibooks/en/a/a8/Openscad-sphere.jpg)

Thank you in advance
att. Rafael

**Comment by RRorg** [comment]
did you try the `calibrationThreshold` parameter?

**Comment by rafaelnco** [comment]
Hey @RRorg! No, I have not tried this parameter yet but would love to see a working demo!
