### ISSUE TITLE
Issues on firefox - laggy animations

### ISSUE THREAD

**Issue by Avaroth** [wagerfield/parallax#146]
Could you please have a look at http://marcel60.ch and test it in firefox? On all major browsers the page is JUST AWESOME. So thanks for your script. But on firefox it lags horribly.

The page is a birthday page for a friend of us :) feel free to give feedback ;)

**Comment by dt1973** [comment]
@Avaroth 

Creating a reduced test case is the best way to debug problems and report issues. Read http://css-tricks.com/reduced-test-cases/ on why they’re so great.

- A reduced test case clearly demonstrates the bug or issue.
- It contains the bare minimum HTML, CSS, and JavaScript required to demonstrate the bug.
- A link to your production site is not a reduced test case.

Creating a reduced test case is the best way to get your issue addressed. They help you point out the problem. They help us debug the problem. They help others understand the problem.

**Comment by MkBeeCtrl** [comment]
For me it lags at firefox, Edge and IE 11, where Edge and IE11 case looks like slideshow.

My parallax is pretty simple, 3 layers in one section initiated with **parallax('enable')** using default settings.

Please take a look: http://beectrl.com

**Comment by RRorg** [comment]
I've pushed some performance improvements to the master branch, please check them out and reopen this issue if performance problems persist.

**Comment by cavemon** [comment]
@Avaroth 

I noticed the animations were a bit jittery in Firefox.  This is a constant issue that I've had with Firefox when doing 3d animations.  Often times applying a slight rotation to the element has fixed this for me, so I modified setPosition only when in Firefox.  This isn't the best solution since my code may be invalid if the plugin ever updates... but it'll work as long as I lock down parallax.js version in my package.json file.

`var isFF = !!navigator.userAgent.match(/firefox/i);

    if (isFF) {
        Parallax.prototype.setPosition = function(element, x, y) {
            x = x.toFixed(this.precision) + 'px';
            y = y.toFixed(this.precision) + 'px';
            if (this.transform3DSupport) {
                this.css(element, 'transform', 'translate3d('+x+','+y+',0) rotate(0.02deg)');
            } else if (this.transform2DSupport) {
                this.css(element, 'transform', 'translate('+x+','+y+') rotate(0.02deg)');
            } else {
                element.style.left = x;
                element.style.top = y;
            }
        };
    }`

**Comment by aaronpowered** [comment]
It has horrible performance on the latest Firefox Quantum too :(
My example: http://rentyz.hu/
On Chrome & Chromium it works really smooth.

**Comment by paulzz3000** [comment]
@aaronpowered it works fine in FF Quantum 60.0.2 on my iMac
