### ISSUE TITLE
Problem with images not scrolling on Y axis

### ISSUE THREAD

**Issue by analxlogik** [wagerfield/parallax#148]
Hi,
I've been using parallax.js and everything worked quite okay. Except that my images doesn't move at all on the Y axis, they only respond to the X axis... Do you know how to fix it, where should I look ?

Thank you !

**Comment by de3web** [comment]
I'm having the same issue. 

I have multiple instances throughout my site using parallax. On my home page everything works as expected, both the Y and X axis respond. On every other instance of the parallax only the X axis responds. 

I've compared the code and there appears to be **nothing** different about the two installations other than the content that loads after the closing divs. They even use the same function call.

Any idea what might be happening here?

**Comment by smbln** [comment]
Same problem here :(

**Comment by iwannabaa** [comment]
I just installed the plugin and my elements are just moving on the X axis as well.

**Comment by iwannabaa** [comment]
@de3web @smbln I figured it out. In my case the container element (ul) had no height set. I set some height to the element and now it is working.

**Comment by smbln** [comment]
Hmmm, doesn't work for me... Do you use a height in px?

**Comment by de3web** [comment]
@iwannabaa Rainbow barf!! Thank you sir, this works perfectly for me.

@smbln I'm using a px height. Haven't tested on %. Let me know if it still doesn't work for you.

**Comment by smbln** [comment]
Still doesn't work.

**Comment by de3web** [comment]
Do you mind posting your css and the container css? I feel like we can find a solution for this.

Also to make sure... your options are all sound right?

calibrateX: true,
limitX: false,

**Comment by iwannabaa** [comment]
I used height: 100% because the container element has its own height. That might help.

**Comment by smbln** [comment]
Thank you for your support.
Here are the files:
[parallax.zip](https://github.com/wagerfield/parallax/files/311541/parallax.zip)

br 
smbln

**Comment by de3web** [comment]
@smbln Hey, it worked immediately when adding a set height to the ul.

ul#scene {
height:250px;
}

Here's a gif

![demo2](https://cloud.githubusercontent.com/assets/5232380/16016913/2d741d30-3152-11e6-9f04-24c6593ab46f.gif)

**Comment by smbln** [comment]
Fantastic! You made my day!!
