### ISSUE TITLE
Image scrolling parallax effect is not working

### ISSUE THREAD

**Issue by muuvmuuv** [wagerfield/parallax#149]
I tried to setup parallaxjs for a simple image scroll parallax effect. So I gave my image wrapper the parallax class and a data-oging-y:

```
<wrapper class="parallax" data-origin-y="1">
   <img src="">
</wrapper>
```

Now I init parallaxjs with jquery:

```
$('.parallax').parallax();
```

So what did I do wrong ? My wrapper is absolute inside an owl-carousel as a background. I looked via the developer chrome tool to check if I styled something wrong. But parallaxjs is not transform the origin of the parallax element..

**Comment by RRorg** [comment]
This is not a scroll parallax library.
