### ISSUE TITLE
Not working on my Safari (Iphone 4S - IOS 5.1.1)

### ISSUE THREAD

**Issue by blackrosezy** [wagerfield/parallax#15]
Nothing happen. Must be something wrong?

**Comment by tylerswartz** [comment]
The issue still appears to be happening on iOS safari for iphone. Safari on the iPad works fine. Any ideas?

**Comment by tylerswartz** [comment]
correction, it appears to work on iphone 6, but not iphone 5. I will check my software updates on the 5 and see if that fixes it.
