### ISSUE TITLE
Can scale-x or scale-y be applied only for a particular layer ?

### ISSUE THREAD

**Issue by pravin-d** [wagerfield/parallax#151]
Can scale-x or scale-y be applied only for a particular layer ? as opposed to the whole scene..

**Comment by DasonCheng** [comment]
how you tackle the problem？I have the trouble

**Comment by pravin-d** [comment]
Not yet handled it man.. I guess U can hack it at the DeviceOrientation event. But thats not fool proof and was giving me a lot of perf issues.. so had to discard it

**Comment by wagerfield** [comment]
What are you trying to achieve? Having a scene with _just_ one moving layer, or having a scene with multiple layers but one of those layers moves a lot more or less than the others? For both of these cases, you can simply set scale x and y to whatever the max amount of motion you want and then use layer depth on each of the layers to control how much they move. There is an in-depth explanation in the README about how the amount of motion for each layer is calculated based on the combination of these values.
