### ISSUE TITLE
npm install parallax doesn't contain assets

### ISSUE THREAD

**Issue by anthony-dandrea** [wagerfield/parallax#152]
After a `npm install parallax --save-dev` I'm only seeing a package.json file. No other files present.

**Comment by SteveEdson** [comment]
I think this is because `parallax` in npm is actually pointing to https://github.com/cocos2d/cocos2d-html5, not here.

Would be good to have this as part of npm though.

**Comment by wagerfield** [comment]
Please see https://github.com/wagerfield/parallax/issues/162
