### ISSUE TITLE
Cannot run on IOS

### ISSUE THREAD

**Issue by longto** [wagerfield/parallax#155]
I test your libs on IOS and it cannot run.
I check that IOS fire event : :DeviceMotionEvent" that you lack.
I listen event devicemotion and it work like a charm.

`Parallax.prototype.enable = function() {
    if (!this.enabled) {
      this.enabled = true;
      if (this.orientationSupport) {
        this.portrait = null;
        window.addEventListener('deviceorientation', this.onDeviceOrientation);
        setTimeout(this.onOrientationTimer, this.supportDelay);
      } else if (this.motionSupport) {
        this.portrait = null;
        window.addEventListener('devicemotion', this.onDeviceMotion);
        setTimeout(this.onMotionTimer, this.supportDelay);
      }
      else {
        this.cx = 0;
        this.cy = 0;
        this.portrait = false;
        window.addEventListener('mousemove', this.onMouseMove);
      }
      window.addEventListener('resize', this.onWindowResize);
      this.raf = requestAnimationFrame(this.onAnimationFrame);
    }
  };`

**Comment by hambos22** [comment]
Can you tell me please how you fixed it? Which part of the code? Thanks

**Comment by pascalwacker** [comment]
Hi @longto I've tried it, but now there's a missing function: `onMotionTimer` could you supply that one too? Thanks

**Comment by RRorg** [comment]
@longto has submitted a pull request that seems to fix this issue:
https://github.com/wagerfield/parallax/pull/156
