### ISSUE TITLE
Can this be used as a background?

### ISSUE THREAD

**Issue by anatchim** [wagerfield/parallax#158]
Hi there,

I apologise in advance if this doesn't work as a forum, and if this does belong here...

I am a designer, and not a programmer, therefore I search and try to addapt scripts that fit what I have in mind for my projects (my skills are quite basic in programing)...

I've bumped into this parallax script, and in a first phase, I managed to addapt it to my needs (going from the example given in the download file "simple.html") - wich would be using the script as a background - with this result, that seems to work beautifully wherever I tested it:
(http://coresaocubo.pt/parallax/

However, when I try to add it to the website design, I don't get quite the result I expected, as I can't seem to get rid of vertical scrolls (because the images I'm using are big):
(http://coresaocubo.pt/parallax/index-teste-1.html

(...and I can't use overflow-y: hidden; on the body, because when the time comes to add the contents, it wouldn't scroll down)

It would be great if I could add something like this to the .container div:

  height: 700px;
  overflow-y: hidden;
  overflow-x: visible;

but obviously this doesn't work as according to the CSS3 spec "some combinations with ‘visible’ are not possible"... 

I've read somewhere that to make it work, I'd have to make a separate wrapper with overflow-y: hidden for the container div, and I did something like:

```
.main-container {
  overflow-y: hidden;
}

.second-container {
  width:100%;
  height: 700px;
  overflow: visible;
}
```

and

```
<div id="main-container">
  <div id="second-container">
    <div id="container">contents here</div>
  </div>
</div>
```

but still doesn't seem to work, I still have the vertical scroll because of the background images used, and it starts behaving oddly on older browsers...

...I am about to just give up and go with a static background image, but I can't seem to feel that I'm so close to what I'd like to achieve, that I'm just plain sad when I think on giving up.

any suggestions?...

Thank you so much,

Ana

**Comment by RRorg** [comment]
I do realize this issue is a bit older, but since it's still open, try adding this to the wrapper class:

```
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
```

you will need to adjust the layers, but this should do the trick
