### ISSUE TITLE
Is it possible to embed such animation into an ebook?

### ISSUE THREAD

**Issue by bogdandragomir** [wagerfield/parallax#161]
I think about creating children books on iBooks or other platform using this kind of animations.
Sometime I saw some example ebooks made by hand with Java Script. Do you know if it is possible to embed parallax in ebooks?

Thank you very much for making this library open source!

**Comment by RRorg** [comment]
That question is not really referring to the library, but yes, it seems you [can actually include HTML5 widgets in iBooks](https://support.apple.com/en-us/HT204433)
