### ISSUE TITLE
Put this in NPM

### ISSUE THREAD

**Issue by marcofugaro** [wagerfield/parallax#162]
I wanted to use this plugin in a project, but was shocked when I found out that this isn't on NPM.

Please put it up and maybe call it `parallax-js`

**Comment by Milewski** [comment]
hahah i was just struggling why my everything wasnt working.. i couldnt even initiate the object.. when i come here to see that parallax is not on npm .. and i download parallax.js which is completely non-sense.... by the way u could always do `npm install https://github.com/wagerfield/parallax --save` if u wish...

**Comment by marcofugaro** [comment]
Cool thanks @Milewski,  but can you actually import it? I think it needs a `main` field in package.json

**Comment by Milewski** [comment]
You can import it.. You can do like this require('parallax/path/to/the/main/js') or using the import syntax.. The parallax will point to the node_modules/parallax and then you just have to dig in to find which is the final js file u want to mix in..

**Comment by marcofugaro** [comment]
Oh yeah you're right...

**Comment by 0x80** [comment]
Installing from github will not give you semantic versioning, so your (production) build can break at any time.

**Comment by Milewski** [comment]
it does sticky to latest commit hash... thats said.. every time you will get the same version... the only disadvantage is that running `npm upgrade` wont get any further versions as it is sticky to that commit hash... but in general.. it wouldn't lead to any build breakages...

**Comment by 0x80** [comment]
@Milewski How does it stick to the latest commit? My package.json seems to only records a link to the repository, without a commit hash. I therefor assume npm fetches the latest commit always when doing a fresh install.

**Comment by Milewski** [comment]
@0x80 uhm thats true.. interesting i used to see those hashes in my packages before.. maybe old npm version did that and this behavior might have changed.. anyway.. even so u could explicit add the hash manually 

by tag

```
npm install https://github.com/wagerfield/parallax.git#v2.1.3 --save
```

by commit hash
```
npm install https://github.com/wagerfield/parallax.git#8bdc2aa981c42731e6b7c0056e79a6a4d2cca016 --save
```

**Comment by wagerfield** [comment]
Parallax was on NPM for some time, but for whatever reason NPM removed it. Originally it was published on NPM as `parallax`, but since its mysterious removal, another package has been published under this name. I have now re-published this library on NPM as `parallax-js` as suggested. Apologies for the delay.

**Comment by 0x80** [comment]
@Milewski I remember having seen those before too. I am guessing an older version of NPM used to add them.

@wagerfield Weird that they would do that without announcing or discussing it first. Anyway thanks for adding it again!
