### ISSUE TITLE
Anchor Tags not working

### ISSUE THREAD

**Issue by yazeedabalkhail** [wagerfield/parallax#164]
I'm having an issue where anchor tags are not clickable nor does it show that it can be clicked. I have the parallax done on the who page, and the anchor is somewhere in the middle. How can i get it to work?

Thank you and wonderful work!

**Comment by DavidBruchmann** [comment]
Links in general are working, so you've a special issue and should provide some code or a link.
Here is a simple page with parallax, perhaps a look into the code helps you already: https://barlians.com

**Comment by wagerfield** [comment]
If your anchors are behind other elements in a scene, you won't be able to click on them _unless_ you set `pointer-events: none` on any elements in front of the layer that contains your anchors/interactive elements:
```
// HTML
<ul id="scene">
  <li class="layer" dataDepth="0.00">
    <img src="background.png"/>
  </li>
  <li class="layer" dataDepth="0.50">
    <a href="#"/>I'm now clickable</a>
  </li>
  <li class="layer ghost" dataDepth="1.00">
    <img src="foreground.png"/>
  </li>
</ul>

// CSS
.ghost {
  pointer-events: none;
}
```

Notice the addition of the `ghost` class to the foreground layer (containing foreground.png)
