### ISSUE TITLE
Demo not working in landscape mode

### ISSUE THREAD

**Issue by efreibe** [wagerfield/parallax#168]
Tested with latest chrome in android.
If you slightly tilt cell phone in landscape mode, the scene scrolls abruptly to one side.
Slightly tilting backwards scrolls to the other side.

**Comment by RRorg** [comment]
Could you please give me additional information on what device you're using, and which demo?

**Comment by efreibe** [comment]
My device is an LG G3 with Android 6.0
Chrome version is 55.
I was talking about the demo pointed by
http://wagerfield.github.io/parallax/

**Comment by RRorg** [comment]
Sadly I couldn't reproduce your issue, but I suspect it might have something to do with wrong calibration. Is this happening every time or depending on what orientation the phone has while loading the web app?

**Comment by efreibe** [comment]
I've recalibrated the cell phone but nothing changed.
Tested with other cell phones in landscape mode.
I've discovered that you need to tilt the upper border some degrees towards
you.
It made clear that it will not be a problem for a "non laid" person (using
the cell phone correctly).
You can close the issue.

**Comment by RRorg** [comment]
With a tiny bit of acrobatics I was able to reproduce the bug with the phone not acting correctly if you're using it over your head 😋 

Will try to fix this!

**Comment by efreibe** [comment]
Don't ask how I figured it out! 😉
Thank you very much!

**Comment by hellosaturn** [comment]
Greetings!
Any news on fixing this bug?
Noticed it on iOS devices too. Portrait and Landscape mode. 
Very noticeble and irritating if you’re in bed or on a couch.
Thanks!

**Comment by alaouimehdi1995** [comment]
Try this: https://github.com/alaouimehdi1995/JS-Parallaxe (Documentation is not written yet, but the demo shows how ti work with it)

**Comment by RRorg** [comment]
@hellosaturn
I will try to look into it, not sure what can be done about it, but there has to be a way :) 

@alaouimehdi1995 
Github has no messaging function and you don't have an email address on your profile, so I'll have to do this public again. Sorry for that.

We had this exact exchange before, I deleted your copy-paste post from all issues but this one, and this is the last time I will talk to you about this. Your project does not solve the problems of any of the issues you posted it in. It is using code and assets from our repository without giving credits. It actually performs worse and has less cross-browser-device-compatibility.

You are more than welcome to contribute, discuss, learn, ask questions, open pull requests, criticise, fork the repo, use it in your open source project, use it in closed source projects, sell it, whatever you want. Yes, the MIT license means you **don't need to** give credit to anyone (not doing so might be considered bad style by professionals, but it's your call). And yes, if you actually created something that might solve the user's problem, I would be happy to see you share it with us!

But I will not tolerate you spamming our forums. If you want to get your name out there, which you are eager to and seems to be your main goal, honest contributions to open source projects are the right way to go! But what you are doing right now is neither honest nor a contribution.

Sorry for being so harsh with you, it seemed better than just banning.

**Comment by alaouimehdi1995** [comment]
https://github.com/alaouimehdi1995/JS-Parallaxe/commit/7b3a20ee4ba4c62a4ccf9232aa23a5a33afc683d
That's what I was talking about, I've fixed the issue month ago, It's not a spam. For information, I'm using png assets from your project, not code. I've added my email address on my profile, if you wanted to answer there.
