### ISSUE TITLE
clipRelativeInput not working

### ISSUE THREAD

**Issue by rodrigobell** [wagerfield/parallax#169]
From what I've tested, the clipRelativeInput option does not work. I'm building a scrollable webpage so this would be nice to have for improved performance once scene is out of view.

Amazing work, thank you!

**Comment by RRorg** [comment]
I'm afraid you're expecting something else from the clipRelativeInput option than what's it currently doing. Please check `examples/relative.html` for the effects of clipRelativeInput.

The argument means the mouse input is clipped to the maximum value of what would be possible inside the container element - but it's still active even when the cursor is not over it.

**Comment by rodrigobell** [comment]
I see, thank you for clarifying that for me. I'll use the API's disable function instead.

**Comment by nicooprat** [comment]
That would be a nice feature to have btw!
