### ISSUE TITLE
events within scene

### ISSUE THREAD

**Issue by rodrigobell** [wagerfield/parallax#170]
Is it possible to preserve event listeners for elements within layers of a scene?

I'm using hover events on some p tags implemented using `mouseenter `and `mouseleave`, but these no longer work after adding them to a parallax.js scene.

**Comment by RRorg** [comment]
Sorry for the late reply, @rodrigobell 

Have you checked out the `interactive.html` demo? This is not a case of Javascript event handlers, but merely HTML elements overlapping. The interactive demo shows how to solve this using absolutely positioned child elements, so the parent wrappers collapse and won't overlap their siblings.

**Comment by RRorg** [comment]
You could also use `pointer-events` to disable them for the layers and only reactivate them for interactive elements, via CSS.

Please feel free to reopen this issue if there are any questions left.
