### ISSUE TITLE
Working on v3 right now

### ISSUE THREAD

**Issue by RRorg** [wagerfield/parallax#171]
Those interested can check out my work on the new ParallaxJS version in the [#v3 branch](https://github.com/wagerfield/parallax/tree/v3). It should be fully backwards compatible to the current master build, except for the following differences:

- jQuery plugin is gone, do `new Parallax($(selector).get(0))` instead of `$(selector).parallax()` if you have to
- Browser support for very old browsers (<1% in browserslist) could be gone (Feedback please)
- The priorities of Parallax parameters explicitly given in the constructor call and those defined in HTML data attributes have been switched, JS will now overwrite data attributes
- more to come...

I will not be accepting any more pull requests for the current master branch, but you're all more than welcome to contribute to the new version, be it with code or with feedback and suggestions 🙂  Full backwards compatibility especially to all versions of Internet Explorer is not in my scope, though I am more than willing to fix relatively easy-to-solve problems with old browsers when pointed out to me.

TODO:
- [x] Live preview/reload for development
- [x] Make use of ES6 syntax
- [x] Remove built files from repo
- [x] Refactor code and dependencies
- [x] Better dependency management for dev and build, gulp-free build on npm install
- [x] parallax should be able to be require'd
- [x] Make ready for distribution via npm, including npmignore
- [x] Readme needs to reflect all new/changed features and workflow
- [x] Do some beautiful branding stuff sometimes maybe?

- [ ] Better/more beautiful examples
- [ ] Implement non-breaking feature requests by the community

**Comment by jamaladdeen** [comment]
Are you considering a tilt effect too? I can tell you that it is very popular these days.

**Comment by MentalGear** [comment]
@RRorg, Awesome !
Looking forward for v.3 - would you like giving a status update ? :)

**Comment by RRorg** [comment]
Hey friends, sorry for the wait!

Will try to get around to releasing it as soon as possible. There are still a few smaller community-contributed fixes I need to apply, as well as non-breaking feature requests I'd love to have in a shippable state before the official release.

If you already want to use v3 in your webapp, that's no problem, it is in a (nearly) fully usable state now. Simply do `npm install wagerfield/parallax#v3` and do `const Parallax = require('../../node_modules/parallax-js/src/parallax.js')` or CommonJS-style import if you prefer.  
I did not yet get around to fixing the build process, so `require('parallax-js')` will fail until I find the time to get this sorted out. As always, I'd be thankful for pull requests.

**Comment by MentalGear** [comment]
Thanks for all your work, RRorg.
Just wanted to say that your library is amazing and keep up the good work ! ✌️

**Comment by RRorg** [comment]
I can (by far!) not take all the credit - @wagerfield did amazing work and so did the community with their contributions ❤️  thank you!

**Comment by ruchern** [comment]
Branch v3 looked to be packed with some awesome new features. The best part I like is the ES6 syntax and doing away with JQuery as much as possible.

Looking forward to see this getting merged into master soon!

**Comment by RRorg** [comment]
It's on master now, thank you to all the lot of you that contributed with code, pull requests, hints, tips, ideas, questions and so on! Please feel free to open issues if you have any requests or problems!
