### ISSUE TITLE
Missing Semicolon

### ISSUE THREAD

**Issue by auguststurm** [wagerfield/parallax#172]
It's a quick fix, add a semicolon and it builds without error.

Below is the output from gulp:

source/parallax.js
line 496  col 4  Missing semicolon. ✖ 1 problem

**Comment by RRorg** [comment]
Since I'm already working on v3, I won't make adjustments to the current master branch anymore - that's merely the linter complaining, the code should build without problems 🙂

**Comment by auguststurm** [comment]
Awesome, and yes I totally understand and agree! Excited to learn more about v3!

**Comment by RRorg** [comment]
Check out the #v3 branch then, it's already up on Github - I'd be really thankful for thoughts and contributions! 😁
