### ISSUE TITLE
<parallax-js> custom element / web component?

### ISSUE THREAD

**Issue by oneezy** [wagerfield/parallax#176]
This is more of a _new project_ more then a _feature request_, but i think it would be cool to create a
`<parallax-js></parallax-js>` custom element for the up and coming [Web Components](https://www.webcomponents.org/) standard.

I might just give it a go myself :D

**Comment by RRorg** [comment]
Cool idea, I'll gladly accept pull requests adding Web Component support, as long as we can somehow polyfill them without loss in performance and compatibility.
