### ISSUE TITLE
y-axis does not work with fullpage.js

### ISSUE THREAD

**Issue by jamaladdeen** [wagerfield/parallax#177]
Hey,

nice plugin, really appreciate your work! I am using it with Fullpage.js but the y-axis movement of the mouse is not registered. Do you know why and how to solve it?

**Comment by RRorg** [comment]
I'd be happy to look into it - do you have an (preferably minimalistic) example of the problem?

**Comment by jamaladdeen** [comment]
I will come back at it as soon as I met a deadline, didn't forget you.

**Comment by RRorg** [comment]
@jamaladdeen feel free to reopen this issue if this is still a problem!
