### ISSUE TITLE
Dependency was not found in webpack

### ISSUE THREAD

**Issue by ruchern** [wagerfield/parallax#179]
```
This dependency was not found:

* parallax-js in ./resources/assets/js/app.js
```

Any workaround for this?

**Comment by RRorg** [comment]
I need more information to help you - what's your build setup? How do you include parallax? Which version?

**Comment by ruchern** [comment]
I just installed it via npm and require('parallax-js'). Usually in my IDE, I am able to click on the package and redirect me to the file, but not this case.

I have also found a temporary work around by adding `"main": "source/parallax.js"` in `package.json` of this package.

**Comment by RRorg** [comment]
Great! This should be solved in the v3 version.

**Comment by ruchern** [comment]
@RRorg Thanks!
