### ISSUE TITLE
Layer class isn't being found by javascript?

### ISSUE THREAD

**Issue by thedonquixotic** [wagerfield/parallax#185]
Hey, so I'm new to development, used to be a designer, trying to integrate this project into a wordpress project, and having some problems. 

I started by putting the JS in the header and the init script in the footer section at the end of the < body >. 

I'm getting this javascript error when I run the parallax function. Don't get why it's happening though. 

`Uncaught TypeError: element.getElementsByClass is not a function`

**Comment by alaouimehdi1995** [comment]
try this: https://github.com/alaouimehdi1995/JS-Parallaxe/
(I haven't yet written the documentation, but the examples shows everything)

**Comment by thedonquixotic** [comment]
Tried the examples and standard index.html and neither really worked :( 

But I asked a friend and somehow my JS file got edited so that instead of saying getElementByClassName into getElementByClass   Which obviously isn't a real javascript function so it wasn't working. Now it works fine. Woo!
