### ISSUE TITLE
Shouldn't relativeInput/clipRelativeInput be configurable via HTML data attributes?

### ISSUE THREAD

**Issue by lbssousa** [wagerfield/parallax#186]
Reading `parallax.js` source code, I can find that every  behaviour can be set via either Javascript or HTML data attributes, **except** `relativeInput` and `clipRelativeInput`, which are configurable via Javascript only.

Is there any reason for this asymmetry? Shouldn't these behaviour be configurable via HTML data attributes as well?

**Comment by RRorg** [comment]
Thanks for the notice, I fixed this in v3!
