### ISSUE TITLE
Update npm package on https://npmjs.com

### ISSUE THREAD

**Issue by ruchern** [wagerfield/parallax#189]
This has not been updated for a while now. Since v3 is now pushed to master, perhaps this might be a good time to do it? 

https://www.npmjs.com/package/parallax-js

**Comment by rene-machel-razorfish** [comment]
Upvote

**Comment by RRorg** [comment]
good call, waiting for @wagerfield to push the button :)

**Comment by ronal2do** [comment]
Greater updates

**Comment by mattclough1** [comment]
+1 for this

**Comment by RRorg** [comment]
I mailed him, but he might be busy with private matters - in the meantime, we have to use `npm install https://github.com/wagerfield/parallax/`

**Comment by ruchern** [comment]
@RRorg Thanks for the update!

**Comment by rene-machel-razorfish** [comment]
@wagerfield, have you got time for this please?

**Comment by RRorg** [comment]
done!

**Comment by ruchern** [comment]
Thank you @RRorg
