### ISSUE TITLE
Multiple parallax in different sections.

### ISSUE THREAD

**Issue by didacus** [wagerfield/parallax#192]
I wish to have a parallax effect for each of the sections in the HTML, unfortunately only the first parallax works at the moment. Is it possible to create multiple parallaxes using `parallax.js`? If so, how can I achieve that?

Thank you in advance.

HTML
```
  <div id="fullpage">
    <section data-anchor="01" class="active vertical-scrolling">
          <ul id="scene">
            <li class="layer" data-depth=".5"></li>
            <li class="layer" data-depth="1"></li>
          </ul>
    </section>
    <section data-anchor="02" class="vertical-scrolling">
          <ul id="scene">
            <li class="layer" data-depth=".5"></li>
            <li class="layer" data-depth="1"></li>
          </ul>
    </section>
  </div>
```

**Comment by RRorg** [comment]
There can only be one element with a specific ID. Give them different IDs and create a Parallax instance for each of them.

**Comment by didacus** [comment]
Perfect. Thanks!

**Comment by RRorg** [comment]
Glad to be of help! If you need anything else, feel free to open another issue :)
