### ISSUE TITLE
 RRorg your release last week broke everything

### ISSUE THREAD

**Issue by tylerjackson5** [wagerfield/parallax#193]
none of the examples work.

everyone download the release before RRorg that was by wagerfield

**Comment by RRorg** [comment]
Could it be that you forgot to do `npm install`? Am 08.05.2017 10:13 vorm. schrieb tylerjackson5 <notifications@github.com>:none of the examples work.
everyone download the release before RRorg that was by wagerfield

**Comment by RRorg** [comment]
hey @tylerjackson5 could it be that you forgot to do `npm install`?

Please give a more accurate error description and if possible the console logs, so we can see what exactly your problem is.

**Comment by tylerjackson5** [comment]
That might be it, was hoping it would act as simple linked files like previous releases so I could make a lean prototype. This is what my page appears as
![screen shot 2017-05-08 at 6 00 43 pm](https://cloud.githubusercontent.com/assets/4520300/25799788/0c2b99a8-3419-11e7-8b54-da0d145c6b47.png)

**Comment by RRorg** [comment]
Oh yes, I could've made that more clear - please refer to the section *Build* in the Readme.

First `npm install` and then `gulp` should work 🙂  but a good call, I was too focused on making things easier for devs and contributors. Maybe a hosted version of the examples would be good for less advanced users? Please feel free to suggest what you think would work best

**Comment by tylerjackson5** [comment]
Thanks for the response man, appreciate it. Yea for guys like me it would be super helpful if there was a version that could be packaged up and deployed very quickly to get our ideas across. If i can email a package to someone and only have to say 'open this file in a browser' it usually saves lots of time. Thanks again for the hard work.

**Comment by RRorg** [comment]
I am sorry for the issues you faced! Updated the [release](https://github.com/wagerfield/parallax/releases/tag/v3.0) with a `compiled-with-examples.zip` file, which can be simply opened in the browser without any precompile steps.

Please feel free to open another issue if there is anything else you need help with.
