### ISSUE TITLE
Improve device orientation detection/fallback to device motion

### ISSUE THREAD

**Issue by lbssousa** [wagerfield/parallax#194]
Some low-end mobile devices (like my old Moto E 1st gen, which doesn't have a gyroscope) may give a "false positive" for device orientation: it passes the `window.DeviceOrientationEvent` availability test, but `deviceorientation` event data `alpha`, `beta`, and `gamma` are always `null`, so that parallax doesn't work at all for these devices.

Please go further in device orientation event detection, checking whether rotation data `alpha`, `beta`, and `gamma` are `null`, and falling back to device motion event if it's the case (note, however, that even `devicemotion` event's `rotationRate.alpha`, `rotationRate.beta`, and `rotationRate.gamma` may also be `null`, so that, in the last case, one should fall back to x/y/z acceleration data).

There's a simple HTML test page which can be used to test a mobile device's motion/orientation capabilities, whose code is published at [mobiForge](https://mobiforge.com/design-development/html5-mobile-web-device-orientation-events). The HTML code is transcribed below:

```html
<DOCTYPE html>
<html>
  <head>
    <script>
    function init() {
      //Find our div containers in the DOM
      var dataContainerOrientation = document.getElementById('dataContainerOrientation');
      var dataContainerMotion = document.getElementById('dataContainerMotion');
 
      //Check for support for DeviceOrientation event
      if(window.DeviceOrientationEvent) {
        window.addEventListener('deviceorientation', function(event) {
                var alpha = event.alpha;
                var beta = event.beta;
                var gamma = event.gamma;
               
                if(alpha!=null || beta!=null || gamma!=null) 
                  dataContainerOrientation.innerHTML = 'alpha: ' + alpha + '<br/>beta: ' + beta + '<br />gamma: ' + gamma;
              }, false);
      }
 
      // Check for support for DeviceMotion events
      if(window.DeviceMotionEvent) {
      window.addEventListener('devicemotion', function(event) {
                var x = event.accelerationIncludingGravity.x;
                var y = event.accelerationIncludingGravity.y;
                var z = event.accelerationIncludingGravity.z;
                var r = event.rotationRate;
                var html = 'Acceleration:<br />';
                html += 'x: ' + x +'<br />y: ' + y + '<br/>z: ' + z+ '<br />';
                html += 'Rotation rate:<br />';
                if(r!=null) html += 'alpha: ' + r.alpha +'<br />beta: ' + r.beta + '<br/>gamma: ' + r.gamma + '<br />';
                dataContainerMotion.innerHTML = html;                  
              });
      }
    }   
    </script>
  </head>
  <body onload="init()">
    <div id="dataContainerOrientation">
      No device orientation data
    </div>
    <div id="dataContainerMotion">
      No device motion data
    </div>
  </body>
</html>
```

**Comment by TheOGL** [comment]
Who uses a moto lol...

**Comment by RRorg** [comment]
I'm really tempted to just agree with @TheOGL and close this issue, but that's just me being lazy 😋 

The hardest part about this is developing without having access to the hardware in question. Keeping this open until someone with a device donates either a pull request or the device itself.

**Comment by lbssousa** [comment]
I've done something similar for the tilting effect in quasar-default-template project:

https://github.com/quasarframework/quasar-template-default/commit/b7a1984db07ded688ae934f2f0b9f17707995c52

I'll try to port this heuristics to parallax and send you a PR.

**Comment by RaSMiY** [comment]
Hi!
It seems I have such a device. What do you need to test?

**Comment by tayloretta** [comment]
It would be great if you could help me. I'm planning to set parallax up into a Nokia 3310. Sounds like a big challenge, right?... R U IN?. xD
