### ISSUE TITLE
Your download zip does not contain proper files

### ISSUE THREAD

**Issue by TheOGL** [wagerfield/parallax#195]
It's missing a dist folder as well as the jquery script. The examples don't even work.

**Comment by TheOGL** [comment]
I had to find an old working script. 

import rqAnFr from 'raf'

this causes errors

**Comment by TheOGL** [comment]
the hoverOnly option is also not even in the script

**Comment by RRorg** [comment]
Run `npm install && gulp` to compile the script. Alternatively, download the compiled-with-examples.zip or compiled.zip if you need a drag-and-drop solution.

hoverOnly was added after the v3 release, so you'll need to clone the repo and compile it yourself. Please let me know if you still face any issues!

**Comment by TheOGL** [comment]
Hmm that's really bad documentation to not explain this. Maybe update the readme.

You shouldn't have to compile a script. It should be ready to use from the zip download. I should
only require one js file. Not everyone uses pointless things like gulp or npm when they don't have it or can't install it.

Just food for thought, make it friendly for everyone.

**Comment by RRorg** [comment]
Yes, you are right, the Readme did/does not make this clear enough. I will see about adding a short section for amateur/hobbyist users on how to get started quickly with precompiled files!  
Unfortunately putting those files into the repo is not feasible for open source projects with multiple contributors, so we'll have to use the releases system for that.

Did everything work out for you now? You can find the `compiled-with-examples.zip` file on the [releases page](https://github.com/wagerfield/parallax/releases), they are ready to be used in your projects 🙂

**Comment by TheOGL** [comment]
Sorry I was so aggressive lol.

An old copy I found online off a site works good for me. www.rock3t.ca.
