### ISSUE TITLE
Absolute div - vertical center

### ISSUE THREAD

**Issue by vierr** [wagerfield/parallax#196]
Hi.
That's a nice script. But I have a problem: Without the script I can vertical center an absolute div with "top: 0; and bottom: 0;" - but with this script the div goes to the top of the site.

Any idea?

**Comment by RRorg** [comment]
If you could upload a minimal example (maybe on Codepen) I would be happy to help you!

**Comment by vierr** [comment]
Here the html and css -> https://codepen.io/OhDerAlex/pen/OmExKP

**Comment by vierr** [comment]
Ok.. i little bit ugly.. but this works ^^->
`#scene {
	width: auto;
	height: auto;
	position: absolute;
	background: blue;

	top: 12%;
	right: 10%;
	bottom: 12%;
	left: 10%;

	.layer-1 {
		position: absolute !important;
		margin: auto;
		top: 0;
		bottom: 0;
  		left:0;
		width: 60%;
		background: red;

		img {
			position: absolute;
			margin: auto;
			width: 100%;
			top: 0;
			bottom: 0;
	  		left:0;
			height: auto;
		}
	}
}`
