### ISSUE TITLE
Missing `NODE_ENV` or `BABEL_ENV` environment variables

### ISSUE THREAD

**Issue by guilhermemarconi** [wagerfield/parallax#198]
I have a `Create React App` ejected environment and got this error when I try to install the package:

```bash
Error: Using `babel-preset-react-app` requires that you specify `NODE_ENV` or `BABEL_ENV` environment variables. Valid values are "development", "test", and "production". Instead, received: undefined.
```

I don't know if anyone else has the same error, that is such annoying because I can't install anything new or update my packages without removing the `eslint` section on my package.json file and putting it back again after it finishes.

**Comment by RRorg** [comment]
Can you provide me with a minimalistic project/repo where I can see that problem myself?

Do you have a valid babel preset installed and in your `.babelrc`?

**Comment by guilhermemarconi** [comment]
@RRorg of course! It's easy to accomplish that.

I ran the `Create React App` as is, and used the `eject` script, so I could manage all Webpack configurations.

I don't know if the actual version is the same I used two weeks ago – I think they released newer versions in the last few days.

About the babel preset, `Create React App` has its own preset installed, the `react-app` (of course lol).

If there's anything I can do to help, count on me! 💪

**Comment by RRorg** [comment]
@guilhermemarconi I have pushed an [update](https://github.com/wagerfield/parallax/commit/31d05382b4d6a6efcd24ea753a6b54e7b6a0a12e), could you try again please? It should be working now :)

**Comment by guilhermemarconi** [comment]
@RRorg it's working! 🎉 

I'm sorry for taking so long to answer. Thank you so much! 😁

**Comment by guilhermemarconi** [comment]
Actually, I thought that it has worked because I did not had any issues on the package installation.
However, when I import the module in my code, I get an error from Webpack that says that the module `parallax-js` wasn't found.

```
Failed to compile.

Error in ./src/Enfinity/Enfinity.js
Module not found: 'parallax-js' in /Users/marconi/Dev/gtx/landing-page/src/Enfinity

 @ ./src/Enfinity/Enfinity.js 14:18-40
```

The `Enfinity.js` source is:

```jsx
import React, { Component } from 'react';
import Parallax from 'parallax-js';
import parallaxLayer01 from '../assets/images/constelacao-fundo01.png';
import parallaxLayer02 from '../assets/images/constelacao-fundo02.png';

class Enfinity extends Component {
  componentDidMount() {
    this.parallax = new Parallax(this.scene);
  }

  render() {
    return (
      <section className="Enfinity">
        <div
          className="Enfinity-scene"
          ref={el => this.scene = el}
        >
          <div className="Enfinity-scene__layer layer" data-depth="0.20">
            <img src={parallaxLayer01} alt="Enfinity GTX" className="Enfinity-scene__img"/>
          </div>
          <div className="Enfinity-scene__layer layer" data-depth="0.60">
            <img src={parallaxLayer02} alt="Enfinity GTX" className="Enfinity-scene__img"/>
          </div>
        </div>
      </section>
    );
  }
}

export default Enfinity;
```

**Comment by guilhermemarconi** [comment]
Just for you to know, I had this warning:

```
Compiled with warnings.

Warning in ./~/parallax-js/dist/parallax.js
Critical dependencies:
1:481-488 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/parallax-js/dist/parallax.js 1:481-488
```

**Comment by RRorg** [comment]
yes, the package points to the compiled file per default. you can try manually including `src/parallax.js` for improved compilation! let me know how it goes :) glad I could be of help

**Comment by RRorg** [comment]
My initial solution is not ideal, because it tends to break other builds, as [pointed out](https://github.com/wagerfield/parallax/commit/31d05382b4d6a6efcd24ea753a6b54e7b6a0a12e) by @chengscott

I was assuming the npm package install process would run independently from the parent project, but that's not the case - for whatever reason the parent project's `.babelrc` is seemingly overwriting the one we provide?

For now, let's ping @pmeinhardt , best Javascript guy I know. Sorry, buddy! 😋

**Comment by pmeinhardt** [comment]
Hi there. I think part of the problem here is that you're using the `install` script (in your `package.json`) to actually build Parallax on the target machine/inside the target project.

This is not recommended and as far as I can see, that is because of issues like the ones you describe. For reference, see also the official docs on [npm scripts](https://docs.npmjs.com/misc/scripts#best-practices).

Instead, you probably want to build, publish the build output and install that - without compiling upon installation.

These are just my two cents here. Let me know if I can be of any more help.

**Comment by RRorg** [comment]
Damn, I've been going this route to try and mitigate the problem that I can't reach matthew and so the npm package won't be updated. Is there any other way, or do I have to bite the bullet and create a new npm package?

**Comment by pmeinhardt** [comment]
Isn't the recommended way of installing Parallax to install from the GitHub repo? Why would you need to create a new package? You can push updates to this repo, right?

**Comment by pmeinhardt** [comment]
If you just name the npm script - say - `build` instead of `install` (which has a special meaning for npm), then you should be fine. Am I missing something?

**Comment by pmeinhardt** [comment]
You would have to add the babelified `dist/parallax.js` version to the repo in this case as far as I can see so people using Parallax via `require`/`import` can use it.

**Comment by RRorg** [comment]
Yeah, I've changed the recommended way to install from this repo, because the npm package is way behind. Adding the compiled version to the repo is a nasty anti-pattern I stopped when I took over this repo, because taking contributions/pull requests becomes painful.

So basically our only options are:
- start a new npm package
- add the compiled js to the repo

or did I miss something?

**Comment by chengscott** [comment]
I vote for starting a new npm package.
Compiled version is not manageable.

Of course, I think the best is to resolve #189

**Comment by pmeinhardt** [comment]
Mmmh, well. In an ideal world - where you have permission to publish this module - you'd really use npm's `prepublish` script to build the babel-transformed version of Parallax and publish that to the npm registry as far as I understand.

Is there really no way to get ownership of the package if you're the one actually maintaining it (see #189 referenced by @chengscott)? Maybe [npm support](https://www.npmjs.com/support) can help if the original maintainer is not responsive anymore?

The last remaining chance I see to resolve the issue at hand in a way that doesn't require a new package: Somehow get babel/babelify to read the correct babelrc? Or pass all the options configured in the babelrc to the command directly via flags and use `--no-babelrc`. (The install script reading the wrong babelrc was the core issue here if I understood correctly.)

But now I'm really out of ideas 😃 

Have a nice weekend.

**Comment by RRorg** [comment]
@guilhermemarconi and @chengscott - can you please try it now? I've rewritten the post-install build process to be selfcontained (thanks a lot for all your time, @pmeinhardt , hope to see you again soon ❤️ ). Please let me know if that fixed your problems - and sorry for the wait!!

**Comment by chengscott** [comment]
Great solution! I think the issue is fixed perfectly
Very thanks to the help of @RRorg and @pmeinhardt 🎉
It's very happy to see my CI work again 😂
