### ISSUE TITLE
stop positioning elements

### ISSUE THREAD

**Issue by lupos** [wagerfield/parallax#199]
not sure if this qualifies as a bur or enhancement but i want to have layers that are not full screen. This is relatively easy to achieve and the effect works how i want it to but i have to comment out the two lines that add "left: 0; top: 0;" in order to make it work. I assume you are doing this as you intend for each layer to be full screen but this short circuit appears to work fine so i guess I'm wondering what the rational is. I was tempted to try and make a PR to "fix" it or at least add the option to disable but wanted to check with you first to see if I'm not understanding something.

**Comment by RRorg** [comment]
The layers are absolutely positioned so they all both
1. span the whole container and
2. are positioned exactly on top of each other

The offset will then be applied by using the available transform-translate attributes.

Think of each layer like a transparent canvas on which you position the elements you want to show at the respective depth. There should be no need to touch the base layer positioning, only adjust the layers' child elements.

**Comment by lupos** [comment]
thanks for the quick reply. I understand that. I guess my concern was that I wanted content between layers and I didn't want a whole layer over top of my interactive content. But I see you have mouse events turned off on all of them which makes sense.

**Comment by RRorg** [comment]
Yes, exactly - if you need to interact with layer child elements, turn mouse events on for those (CSS `pointer-events: all;`). Feel free to reopen this issue if you need help with anything else! :)
