### ISSUE TITLE
Mobile movement incorrect?

### ISSUE THREAD

**Issue by kensoh** [wagerfield/parallax#201]
Hi @RRorg thanks for maintaining and continuing development of this great project!

Recently I notice that the movement on mobile is incorrect. It seems to be opposite of what it should be. For example the webpages I created and Matthew's landing page. For desktop browser the movement appears ok.

But for mobile, movement appears to move in opposite of what is natural. For example tilting left should naturally let us see more of the right side of objects by moving objects left. But object layers move right when tilting mobile device left.

http://tebel.org/gist/interface_automation
http://tebel.org/gist/open-source_software
http://matthew.wagerfield.com/parallax/

I am not sure if it is due to some change in mobile Chrome behavior. If the issue exists back when I made the webpages in March I would have noticed. I am feeling confused, and for now I use [Mobile Detect](https://github.com/serbanghita/Mobile-Detect) to reverse the default values for `data-invert-x` and  `data-invert-y` to make them false for mobile device, so that movement becomes natural.

I'm running on Samsung Galaxy 5 Android Chrome 58.0.3029.83. Posting this issue here to see if anyone else experiences this issue.

**Comment by RRorg** [comment]
Interesting - I'll try getting my hands on different devices and mobile browsers and see if there are discrepancies between their behaviours - then we can see what the best solution would be. What I can do for you is maybe separate the invert options into invert-mouse and invert-motion, if that's any help? Although your MobileDetect solution is pretty clever too!

**Comment by kensoh** [comment]
Thanks @RRorg for your reply! No probs, it might be a big change to split the invert options and requires many users to change their config. Am raising this just to seek your opinion and whether other users experience this.

I have been thinking about it. I guess it depends on the point of reference chosen. Let me try my best to describe what I mean, but an expert in VR will be able to put this across in a better way.

The current setup point of reference assumes the mobile screen is a window into the virtual world of layers. So tilting left, sees more of the 'left' side. My point of reference assumes the mobile screen itself is the virtual world. So tilting left essentially tilts the world around to let us see more of the 'right' side. Though I'm not sure what is the best practice or which way feels more natural to most users.

This might be a non-issue, in the sense that it actually depends on what type of experience the developer wants the user to have, having a window pane into a virtual world, or the virtual world is the phone itself.

**Comment by mykt0ngc0** [comment]
A combination of [matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) and [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) works for me.


```
var isMobile = window.matchMedia('(max-width: 1024px)');

var parallaxInstance = new Parallax(scene, {
  invertX: isMobile.matches ? false : true,
  invertY: isMobile.matches ? false : true,
});
```

**Comment by reneroth** [comment]
thanks for the solution!
