### ISSUE TITLE
Incorrect movement on some devices (tilt up/down moves left/right)

### ISSUE THREAD

**Issue by syrys** [wagerfield/parallax#203]
So, I have been using this package for a long time in different projects, and I recall having this issue since early days (just never posted about it). 

Lets try to explain the issue:
The tilting movement works perfectly fine on my Nexus 6P Chrome (both landscape/portrait), but on my Galaxy Tab S Chrome it does the opposite (tilting up/down makes parallax move left/right regardless of landscape/portrait orientation or using orientation lock, happens 100% of the time). Tests were done using the linked demo page as well as my own projects (so its not a bug on my project). 

Also tested on a Galaxy S8+, and works correctly there too (so its not issue on ALL Samsung devices, probably just some tablets? maybe limited to Samsung tablets?).

Any ideas?

Just to debug this further, i came across this device orientation demo here: http://wellcaffeinated.net/demos/device-orientation

On my mobile (nexus 6P) in Portrait mode: Works as expected.
On my mobile (nexus 6P) in Landscape mode: Incorrect, up/down makes arrow move left/right.

On my tablet (Galaxy Tab S) in Landscape mode: Works as expected.
On my tablet (Galaxy Tab S) in Portrait mode: Incorrect, up/down makes arrow move left/right.

As you can tell, the tablet/mobile works differently in terms of which orientation is "correct".

**Comment by RRorg** [comment]
This seems to be a bug somewhere between Chrome and the device communicating the orientation. Unfortunately, I have no buggy tablet to check this with. If you have any idea how we can detect this bug, I'll gladly try to mitigate it! Maybe you can find another project where this bug does not happen and we can dig into their code and have a look at their solution? 😁

**Comment by wildwerk** [comment]
I'm unfortunately so happy to find this thread, because i have this problem on my Galaxy Note 10.1 (SM-P600).  The last three days i've been searching why this shit happens. Visited some demo sites but everywhere the same issue. Updated Tab firmeware and nothing new :(  What can I do to support your development on a solution for this?
