### ISSUE TITLE
enhancement: allow class name other than "layer"

### ISSUE THREAD

**Issue by lupos** [wagerfield/parallax#204]
So I'm using this is a much larger project and attempting to name space all css classes and `layer` stands out as a fairly generic name. It's unlikely to actually cause an issue but it would be great to be able to pass in an alternative layer class name or a prefix ('my-custom-layer') so the library doesn't dictate code style in anyway.

**Comment by RRorg** [comment]
+1 from me on this. If nobody vetoes, I'd completely remove the JS-side class name requirement. In my opinion, the script should be CSS-agnostic.

**Comment by RRorg** [comment]
No vetoes received, have implemented this suggestion. Thank you! :)

**Comment by caiotarifa** [comment]
This modification broke my code.

The @lupos idea was to be able to **rename** the class **and not** pick up the first descending elements.

_Similar example code:_

```
<div id="scene">
  <img src="..." class="layer" data-depth="0.05">

  <div class="team-one">
    <img src="..." class="layer" data-depth="0.075">
    <img src="..." class="layer" data-depth="0.1">
    <img src="..." class="layer" data-depth="0.125">
  </div>

  <div class="team-two">
    <img src="..." class="layer" data-depth="0.075">
    <img src="..." class="layer" data-depth="0.1">
    <img src="..." class="layer" data-depth="0.125">
  </div>
</div>
```

**Comment by RRorg** [comment]
Is there a reason you need to use containers instead of directly assigning the class names to the layer elements? I could implement an optional class selector for fringe cases like yours if there's no other solution.

**Comment by amateur** [comment]
This modification broke my code as well. This doesn't work for complicated HTML structure. For example I have three different containers which are used for styling and by other JS UI plugins. And I simply can't move the Parallax layer elements to the top of this structure.

I propose overriding layer elements only there are no elements with class `.layer`.

**Comment by RRorg** [comment]
Very good call, sorry to have caused such an inconvenience to you.  
Maybe we could rectify the situation by adding an optional parameter that gets fed to `querySelectorAll`? So for those with special needs like yours, you could add a selector of `.layer`.

Would that work for you, @amateur and @caiotarifa

**Comment by amateur** [comment]
@RRorg, yes, it works for me. Thanks!

**Comment by caiotarifa** [comment]
@RRorg, I think so. Thanks!

**Comment by RRorg** [comment]
Please try the latest commit on master :)

**Comment by amateur** [comment]
It works great! Thanks a lot.

**Comment by RRorg** [comment]
Thanks for your patience and understanding, all! ❤️
