### ISSUE TITLE
Local parallax

### ISSUE THREAD

**Issue by sarambasic** [wagerfield/parallax#205]
How to use parallax only if I hover particularly section? I want to use parallax on some section only when i hover that section of page. Tnx 

I try this :
var scene = $('.js-prlx2')[0];
	var parallax = new Parallax(scene, {
		clipRelativeInput: true,
		relativeInput: true,
		hoverOnly: true,
		inputElement: ('.js-prlx2')[0],
	});

**Comment by RRorg** [comment]
Check out this example:

https://github.com/wagerfield/parallax/blob/master/examples/pages/input_element.html

**Comment by sarambasic** [comment]
Didn't help. 
Yea I saw that mistake.  I understand what i need to do but something missing.

**Comment by RRorg** [comment]
Do you have a live example somewhere or could you put one up on CodePen?

**Comment by sarambasic** [comment]
I will put one togehther and share here. Tnx man

**Comment by sarambasic** [comment]
Live example : https://codepen.io/sarambasic/pen/yXbGRV

**Comment by RRorg** [comment]
Ah yes, the problem is that you're using the v2 version - v3 is not yet on CDN or npm and must be installed directly from the repo or downloaded manually from the [releases page](https://github.com/wagerfield/parallax/releases).

**Comment by sarambasic** [comment]
Tnx, I will give it a try and infom you about the result.

**Comment by sarambasic** [comment]
When i include Source code (zip) i get this error :

![image](https://user-images.githubusercontent.com/10234603/27382965-388406d8-5689-11e7-95cb-2fb248934112.png)

**Comment by RRorg** [comment]
If you want to use `import` or `require`, you'll need to use something like webpack or babel. Else, download `compiled.zip` from the releases, and include it like you did with v2.

**Comment by sarambasic** [comment]
Still nothing. From the start i have v3.
https://github.com/sarambasic/prlx
https://sarambasic.github.io/prlx/

**Comment by RRorg** [comment]
My bad - the inputElement option is not in the v3 release, but was added later! Please try the attached file.
[parallax.zip](https://github.com/wagerfield/parallax/files/1091476/parallax.zip)

**Comment by sarambasic** [comment]
Works like a charm.
