### ISSUE TITLE
Should this project (or its CDN/npm repo) be forked?

### ISSUE THREAD

**Issue by lbssousa** [wagerfield/parallax#206]
It has been over a month since parallax-js version 3.0 was released in GitHub and it's not yet updated in CDN or npm. AFAIK, this is currently on charge of @wagerfield, but it seems far away from the project in the moment (his latest relevant commit to the project is dated from the end of 2014). Since then, @RRorg has became the main contributor of parallax-js.

I wonder if it would be better if @RRorg fork this project, or at least fork its CDN/npm repository, so that it could be kept up-to-date by himself.

**Comment by RRorg** [comment]
I would do it, but this project has +11,500 stars as of now, and I would feel like taking something from Matthew. I could of course keep a fork updated and use this to push to CDN and npm, which would be a good compromise I think!

oh, and thank you all for your trust! :)

**Comment by RRorg** [comment]
I've gained full access to this repo and the npm package, so I'll close this issue :)
