### ISSUE TITLE
Why do you initialize like this?

### ISSUE THREAD

**Issue by 10081677wc** [wagerfield/parallax#207]
updateLayers() {
    this.layers = this.element.getElementsByClassName('layer')
    this.depthsX = []
    this.depthsY = []

    for (let index = 0; index < this.layers.length; index++) {
      let layer = this.layers[index]

      if (this.transform3DSupport) {
        helpers.accelerate(layer)
      }

      layer.style.position = index ? 'absolute' : 'relative'
      layer.style.display = 'block'
      layer.style.left = 0
      layer.style.top = 0

      let depth = helpers.data(layer, 'depth') || 0
      this.depthsX.push(helpers.data(layer, 'depth-x') || depth)
      this.depthsY.push(helpers.data(layer, 'depth-y') || depth)
    }
  }

Hi,
u changed the location of the components.
Why do you initialize like this?

**Comment by RRorg** [comment]
I am not sure I understand the intent of the question - is something unclear, are you encountering problems or having suggestions for improvement?

**Comment by 10081677wc** [comment]
The component using gravity sensing maybe has its own 'left' or 'top' values, so initialization like this will make it in the up-left corner of the page, rather than where it should be.

**Comment by RRorg** [comment]
We're resetting the position of the layer elements only, to ensure correct behaviour.  
The parallax parent element will respect your styling :)
