### ISSUE TITLE
Examples have broken link and images

### ISSUE THREAD

**Issue by abergs** [wagerfield/parallax#208]
None of the examples are runnable.

They have incorrect paths to images and missing css files

**Comment by RRorg** [comment]
You have to either run gulp or download compiled-with-examples.zip from the releases section :)

**Comment by abergs** [comment]
@RRorg Ah, I see. Would be awesome if this was mentioned even more clear, perhaps by a comment in each example and/or in the readme! :)

**Comment by RRorg** [comment]
you're right! tagging this for improvement

**Comment by reneroth** [comment]
Closing this, since I've completely rewritten the Readme. Please let me know if anything needs improvement.
