### ISSUE TITLE
init depths in js

### ISSUE THREAD

**Issue by lupos** [wagerfield/parallax#209]
I like the simplicity of data attributes and I know you can update the value programmatically but my particular use case has different behaviors on different devices so it would be ideal if I could set the depths of each layer at run time rather than hard coding them. Presently I get the value from a template helper which has to be maintained on 2 sets of templates (client/server).

Though more generally i think it just lines up better with how the rest of it is written allowing for simple use via all html config or js if preferred.

Not sure how best to do it but my first thought is a hash of selectors and depths.

**Comment by Splendorr** [comment]
@lupos Could you work around this by setting attributes via js? Check for device, then set the elements' "data-depth" attribute like 

```
var b = document.querySelector("layer1"); 
b.setAttribute("data-depth", "0.8");
```

And then initialize the parallax? I haven't tested this, and it's not as clean as your proposed solution, but might be better than hard-coding multiple templates.

https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute

**Comment by RRorg** [comment]
You make a good point, though I am not yet sure how to approach this - any input and ideas are highly welcome!

For the time being, the approach suggested by @Splendorr might work best - if data changes after initialisation, you can call `Parallax.updateLayers()`  
Or, if you're feeling especially adventurous, directly access and manipulate the `Parallax.depthsX` & `Parallax.depthsY` arrays of your instance. Not saying it's the best of ideas, merely saying it's possible... 😅

**Comment by reneroth** [comment]
^ I'd say this is actually the way to go for now.
