### ISSUE TITLE
Multiscenes and How to parallax only on hover scene?

### ISSUE THREAD

**Issue by salasmx** [wagerfield/parallax#210]
1. Is there a way to have multiple scenes?

2. Is there a way to only move the scene's elements when hovering the scene?
It seems that the event occurs even when the pointer is moving out of the scene.

I would like to have two scenes that can move its elements only when the pointer hovers on each scene. Is that possible?

Thank you!!

**Comment by RRorg** [comment]
1. sure, you can create multiple instances no problem!
2. you're looking for the option `hoverOnly`, best in combination with `relativeInput`

**Comment by salasmx** [comment]
Thank you very much for your quickly response but sorry if I didn't get that.

hoverOnly and relativeInput are set true but I don't see that works.

I would really appreciate your help, maybe you can check my pen and tell me what am I doing wrong. It is possible to you? https://codepen.io/carlosalas/full/QgBbbK/

The scenes are on the bottom of the page.

Thank you!!

**Comment by RRorg** [comment]
you're using the old version of Parallax, please use v3!

**Comment by salasmx** [comment]
I'm having an issue, codepen import what finds on CDNjs but your latest version is not available. So I uploaded your v3 to my amazon s3 bucket but console shows this:

Uncaught ReferenceError: require is not defined at: const rqAnFr = require('raf')
Uncaught ReferenceError: Parallax is not defined at:

var scene = document.getElementById('scene');

var parallax = new Parallax(scene, {
  hoverOnly: true,
  relativeInput: true,
  scalarX: 8,
  scalarY: 8,
  frictionX: 0.2,
  frictionY: 0.2
});


*I've tried with code inline too but same result.

**Comment by RRorg** [comment]
Set Codepen to use the Babel preprocessor and things should work fine for now - I agree, this point has been made numerous times, we need to better communicate when to use which file. Sorry for short replies, I am currently on the move :)

**Comment by betodasilva** [comment]
Same problem here, but I don't use Babel as preprocessor. (I'm not using codepen). Do you have any suggestions?

**Comment by RRorg** [comment]
Please use the compiled versions from the releases section. I will try getting the lib on CDNjs! :)
