### ISSUE TITLE
hoverOnly property seems not to work

### ISSUE THREAD

**Issue by kstalega** [wagerfield/parallax#211]
Hi, 

I've started using your library, and it is great but there is one problem. I cannot have `hoverOnly: true` property working. What is more, when I did `CTRL + F` on your library in version 3.0 there is no property like `hoverOnly`. Is it still suported?

Thank you in advance.

**Comment by RRorg** [comment]
It's not in the v3 release, but was added later - you'll need to check out the current state of the repo and compile yourself - sorry! :/

**Comment by kstalega** [comment]
No problem, will it be included in next official release?

**Comment by RRorg** [comment]
Yes, definitely going to be included in v3.1, I mainly want to rebuilt the Readme from scratch before I release this, though. Too many confusions and issues because I didn't write good documentation for features added... 😅

**Comment by RRorg** [comment]
Finally got around to releasing it! Hope you enjoy!! :)
