### ISSUE TITLE
Doesn't work on Android Chrome?

### ISSUE THREAD

**Issue by robizzt** [wagerfield/parallax#212]
Hello, 
I'm using drag-and-drop JS file, parallax.min.js. I works perfectly on desktop and iOS browsers, but doesn't on Android Chrome. Do I need to include special code for that to work, or is it bug, or am I doing something wrong?

And on Mozzila Firefox, my image turns blue when clicked on it.

This is my code:

`<div id="scene" class="winne">`
`<img src="img/winn-2.jpg" alt="Winnetou" data-depth="0.50" class="layer">`
`</div>`

`<script src="js/jquery-3.2.1.min.js"></script>`
`<script src="js/parallax.min.js"></script>`

`<script>`
`var scene = document.getElementById('scene');`
`var parallax = new Parallax(scene);`
`</script>`

**Comment by robizzt** [comment]
I figured out first problem. Instead of using parallax.min.js, I tried jquery.parallax.js and it works, but only when I click on mobile screen, not when changing orientation of the mobile screen. I want to make something like this: 
http://tutorials.stk.works/examples/parallax/
This works same on every desktop and mobile browser.

**Comment by RRorg** [comment]
Are there errors thrown in your browser's console?
