### ISSUE TITLE
Parallax is not working

### ISSUE THREAD

**Issue by onmarketing** [wagerfield/parallax#213]
Hi guys,

It very URGENT!

I'm doing create parallax website for client project but seem not working. I download your new version. I use jquery.min.js. and here my coding:

**HTML**

```
<div id="container" class="Parallax">
    <ul id="scene" class="scene">
         <li class="layer left" data-depth="0.30"><img src="" alt="...."></li>
         <li class="layer left-1" data-depth="0.80"><img src="" alt="...."></li>
         <li class="layer center" data-depth="0.20"><img src="" alt="...."></li>
     </ul>
</div>
```

**JS**

`var scene = document.getElementById('scene');
var parallax = new Parallax(scene);`

Can you please fix this problem?

Thanks,

Shaun.

**Comment by onmarketing** [comment]
This download that I use: https://github.com/wagerfield/parallax/archive/v3.0.zip

But this is not working, maybe something wrong with it.

**Comment by DavidBruchmann** [comment]
Hava a look at these threads:  
https://github.com/wagerfield/parallax/issues/205  
https://github.com/wagerfield/parallax/issues/212  
https://github.com/wagerfield/parallax/issues/202

**Comment by RRorg** [comment]
What does your browser console say?

**Comment by onmarketing** [comment]
1. Uncaught SyntaxError: Unexpected token import - parallax.js

2. Uncaught ReferenceError: Parallax is not defined at index.html:340

**Comment by onmarketing** [comment]
@RRorg how do I fix this problem? website project deadline is next week.

**Comment by onmarketing** [comment]
@RRorg 

Download plugins: https://github.com/wagerfield/parallax/releases

I use Jquery for website project: https://code.jquery.com/jquery-3.2.1.min.js

Which do I use compiled-with-examples.zip, compiled.zip, or Source code (zip)?

**Comment by onmarketing** [comment]
This one works: https://github.com/wagerfield/parallax/tree/v2.1.3

But Parallax 3 is not working, Any reason why it not working?

**Comment by RRorg** [comment]
You need to download compiled.zip from the releases section if you're not installing via npm and have no compile step in your project's setup :)

**Comment by xelaz** [comment]
I have the same Problem, i can't start parallax in your examples. And i use your compiled script from Release 3.0

**Comment by RRorg** [comment]
@xelaz Please feel free to open a new issue if you still have any problems using the latest version! :)
