### ISSUE TITLE
Parallax won't initialize

### ISSUE THREAD

**Issue by selenir** [wagerfield/parallax#214]
I'm using parallax.js v3, my markup looks like following:
```
<div class="masthead-banner parallax-container">
  <div class="parallax parallax1" data-depth="0.00">
    <img src="some_url" class="layer-blue-baloon">
  </div>
  <div class="parallax parallax2" data-depth="0.50">
    <img src="some_url" class="layer-red-balloon">
  </div>
  <div class="parallax parallax3" data-depth="1.00">
    <img src="some_url" class="layer-slogan">
  </div>
</div>
```
I perform basic initialization as described in docs:
```
var scene = $('.parallax-container').get(0);
var parallax = new Parallax(scene, { onReady: function() { alert('ready!'); } });
```

The problem is that `onReady` function never fires. Container element's style attribute gets some transforms but that's all. None of the children elements actually respond to mouse movement etc. No console errors.

**Comment by RRorg** [comment]
You'll need to compile the latest version for onReady, the callback came after v3 was released - that's faulty documentation (sorry!).
For the rest, I'm not sure why it won't work - seeing as how the container is getting styled you seem to be doing everything right so far. Is there a demo I can take a look at?

**Comment by selenir** [comment]
I recreated all relevant code in [this codepen](https://codepen.io/selenir/pen/wqaZZq).

**Comment by RRorg** [comment]
Ah, you're using the old v2 version, in which each layer needs to have the literal class `layer` applied to it. [see my fork](https://codepen.io/rrorg/pen/zdGVyP?editors=1000)

**Comment by selenir** [comment]
It worked, many thanks! Apparently I was reading example code for wrong version.
