### ISSUE TITLE
how to install it with webpack? 

### ISSUE THREAD

**Issue by Maor44** [wagerfield/parallax#215]
Hello, 
when I run npm install --save https://github.com/wagerfield/parallax in my project folder I get ''Error: not found: git''
git clone --template=***_templates --mirror https://github.com/wagerfield/parallax.git ***\_git-remotes\git-https-github-com-wagerfield-parallax-git-fefc3e4e: undefined
webpack 2. 

Thank you.

**Comment by Naeoth** [comment]
You have to install git on your environment to install parallax-js through npm.

**Comment by RRorg** [comment]
With the latest version, setup and Readme have been improved.

Please feel free to reopen this issue if you still experience any problems.
