### ISSUE TITLE
Firefox issues

### ISSUE THREAD

**Issue by gitguys** [wagerfield/parallax#218]
On Firefox on both Mac Desktop & Android Firefox app, the banner drops differently, less aesthetically sliding down from the top and staying up top as shown below -

![screen shot 2017-08-19 at 7 24 01 pm](https://user-images.githubusercontent.com/11050768/29491299-8c55a2bc-8514-11e7-884b-e3f2c54832d1.png)

Is this a known issue with no fix available?  It's always been this way, I think.

Also, in earlier parallax.js versions it loaded up smoothly on Android Firefox, but now the animations stutter and general movement is extremely shaky.  Still smooth with Desktop Firefox.   Very smooth on Android Chrome, as it was before, however.  Is this a known issue as well with Android Firefox?

**Comment by RRorg** [comment]
See issue #219, I'm not really interested in maintaining the gh-pages branch right now, though I will eventually have to come around and fix this too.

Is the mobile firefox problem happening on the most recent version of the library too? Please keep in mind that the demo page is using an old version of the lib.

**Comment by bfalchuk** [comment]
Firefox Quantum v 57.0 (64 bit) - the banner on the main parallax.js page does not drop down at all.  The library appears to otherwise work ok on v57 . However, I'm seeing an issue with animated gif (works on chrome and edge (windows 10), but not on FF quantum.

**Comment by gitguys** [comment]
> See issue #219, I'm not really interested in maintaining the gh-pages branch right now, though I will eventually have to come around and fix this too.
> 
> Is the mobile firefox problem happening on the most recent version of the library too? Please keep in mind that the demo page is using an old version of the lib.

AT: http://matthew.wagerfield.com/parallax/

The dropdown menu doesn't work at all now with any version of Firefox I've tried on Mac, Windows, nor Android.  Clicking the X button doesn't do anything.
