### ISSUE TITLE
Microsoft Edge - Waves don't move

### ISSUE THREAD

**Issue by gitguys** [wagerfield/parallax#219]
With the Windows 10 MS Edge browser the waves are stuck in place here -

http://matthew.wagerfield.com/parallax/

I tested in a couple different versions of Edge.

**Comment by RRorg** [comment]
Yup, seems the rotateZ-Animation is not working on Edge. Maintaining the gh-pages branch is not really on my list of priorities, though, so maybe @wagerfield might have time to look into it? :) 

If anyone else has an idea how to fix this, please let me know and I'll implement this. I just really don't want to get into debugging this stuff right now.

**Comment by reneroth** [comment]
should be fixed with edge having switched to a real browser engine
