### ISSUE TITLE
Fatal error in Microsoft Edge, when parallax called on SVG element

### ISSUE THREAD

**Issue by romash1408** [wagerfield/parallax#222]
For some reason Microsoft Edge do not support `selector` or `children` for SVG elements.
So, when working with SVG, field `layers` gets undefined [here](https://github.com/wagerfield/parallax/blob/f3eaeba7e3f2e59d600cff03110d6aa0de30331d/src/parallax.js#L288), what leads to error.

**Comment by RRorg** [comment]
Added this problem to the known issues list. Is this a known bug in Edge or intended behaviour?

**Comment by reneroth** [comment]
nothing we can do to fix this, but it's added to the readme. sorry to all edgers out there!
