### ISSUE TITLE
Make browserify a devDependency

### ISSUE THREAD

**Issue by geloescht** [wagerfield/parallax#223]
At the moment, when you install parallax-js via NPM it pulls in all of browserify by default. This leads to a huge number of packages being installed in turn as dependencies of browserify.
If parallax-js was built before publishing to NPM, browserify could be made a devDependency which is only needed when developers want to build parallax-js theirselves.

**Comment by RRorg** [comment]
your username had me confused for a second there! 😋 

You're right, this is a must-do, will try adding a pre publish step as soon as I find enough spare time

**Comment by RRorg** [comment]
I added the precompiled files to npm to remove the need for a compile step. Your feedback is highly welcome, please let me know if anything could be improved!
