### ISSUE TITLE
Cant install with npm 

### ISSUE THREAD

**Issue by TomasRas** [wagerfield/parallax#224]
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! parallax-js@3.0.0 install: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the parallax-js@3.0.0 install script 'npm run build'.

**Comment by RRorg** [comment]
Please try again.
