### ISSUE TITLE
Auto Movement

### ISSUE THREAD

**Issue by gvinson** [wagerfield/parallax#226]
I don't see it anywhere in the docs but is there a way to have the items move around without having to use the mouse?

**Comment by RRorg** [comment]
If any kind of motion detection hardware is available, the library will automatically use the tilt of the device :)

**Comment by gvinson** [comment]
@RRorg I mean on desktop, is there a way to automatically start the animation without mouse movement. I am currently using a css animation to start some animation and using the mouse movement to translate the elements around the screen.

In short, is there a way, on desktop, to start the parallax effect without mouse movement?

**Comment by RRorg** [comment]
I'm sorry, I'm not sure if I'm understanding the scope of the question correctly. So what you're trying to do is basically simulating mouse input, so the parallax effect moves on its own? If that's what you're trying to achieve, I can see about how you could solve that problem, although I'm not sure if this library is the best approach for the job.

**Comment by gvinson** [comment]
@RRorg Correct, that is the desired effect. I believe you are, unfortunately, correct...

**Comment by reneroth** [comment]
I assume you mean the wave effect on the sample page? That's a simple CSS animation.

**Comment by DiegoFelipe** [comment]
yes sir, I mean the automovement effect, everything moving without mouse movement

**Comment by reneroth** [comment]
that is a CSS animation applied to the contents of the parallax layers, can be done with or without this lib :)
