### ISSUE TITLE
dist/parallax.js not found despite being referenced in package.json

### ISSUE THREAD

**Issue by lethak** [wagerfield/parallax#227]
https://github.com/wagerfield/parallax/blob/6ebe9485de01eb082cd95ac1ba929fcded235aba/package.json#L6

The current version broke the following notation:

```
import Parallax from 'parallax-js'
```

I have it working on another project at commit https://github.com/wagerfield/parallax/commit/f3eaeba7e3f2e59d600cff03110d6aa0de30331d

I can try to do:
```
import Parallax from 'parallax-js/src/parallax'
```

But will require the use of babel / Uglify-ES for the minification to work
Using Uglify-JS (2), I get the error:

> ERROR in myfile.js from UglifyJs
Unexpected token: punc (() myfile.js:28901,7]

**Comment by BarryOwens** [comment]
Seems the build step has been removed in this [commit](https://github.com/wagerfield/parallax/commit/f56998f46b4fb6ce806687e6153c6ade36e0be76) 

But package.json still refers to the dist folder

**Comment by RRorg** [comment]
The built process is now run as npm pre publish step, but differing from that previously run as postinstall hook. I'll see about fixing this up!

**Comment by BarryOwens** [comment]
I think this has been resolved now. I can see there is a dist folder again. Thanks!

**Comment by lethak** [comment]
@BarryOwens I don't see it on master atm

**Comment by reneroth** [comment]
it's not committed into the repository, but in npm :)
