### ISSUE TITLE
Any Apache HTML version???

### ISSUE THREAD

**Issue by Freedou** [wagerfield/parallax#228]
Is this script only work for node.js ?

**Comment by RRorg** [comment]
This is a front-end script meant to be run in browsers - nodeJs will not be able to run it due to lack of a DOM.

**Comment by Freedou** [comment]
I run it on a WAMP JavaScript send me error when I run the script especially cause he can't run the 2 first import command of parallel.js on another hand your release section was not available so I need to build the parallel.min.js by my own it could be good for other user repair it.
When I think about it, it could be linked to my issue because I clone directly your git...

**Comment by RRorg** [comment]
Good call, one of the links to the releases section was broken, I fixed this.

**Comment by Freedou** [comment]
Thanks. I'll test it this evening.

**Comment by Freedou** [comment]
Yep everything works perfectly fine thank alot. I think you can close this thread :)

**Comment by RRorg** [comment]
Glad it works for you - let me know if you need help with anything else! :)
