### ISSUE TITLE
Position absolute

### ISSUE THREAD

**Issue by danielgentile** [wagerfield/parallax#230]
I have a logo at the center of my hero placed using position absolute but when I run parallax on it, it resets my position to top: 0 and left: 0.

How can I center my logo using parallax.js?

**Comment by RRorg** [comment]
You can try wrapping it in an absolutely positioned parent container

**Comment by mikekok** [comment]
I tried placing my images inside absolutely positioned parent containers but it still didn't work, I get no parallax effect at all.

With parallax disabled, everything is positioned as expected, but when enabling the instance, `top` is reset to 0 and nothing is moving at all.

```html
<div id="scene">
    <div class="slide" id="slide1"><img src="/img/slide1.png" alt="" data-depth="0.6"></div>
    <div class="slide" id="slide2"><img src="/img/slide2.png" alt="" data-depth="0.6"></div>
    <div class="slide" id="slide3"><img src="/img/slide1.png" alt="" data-depth="0.6"></div>
</div>
```

```sass
#scene {
    position: relative;

    .slide {
      position: absolute;

      &#slide1 {
        top: 50px;
      }
  
      &#slide3 {
        top: -50px;
      }
    }
}
```

**Comment by reneroth** [comment]
please create a functional demo I can check out

**Comment by danielgentile** [comment]
Thanks for the help Rene it worked out

**Comment by reneroth** [comment]
I'll close this issue then. Feel free to post again if you still need help with anything!

**Comment by Zaithe** [comment]
I'm having the same issue as @mikekok described, nothing is moving anymore.

**Comment by reneroth** [comment]
I cannot help you if you do not provide a demo, some code, error logs or whatever else.

The amount of people simply saying "does not work lol" is sometimes slightly annoying. Please keep in mind that I'm providing this free project in my personal time without any material gain from it - while on the other hand, every one of you is very much free to monetise it in whatever way you all wish.

I am under no obligation to make things work, so I'd greatly appreciate it if you could at least try to help me in helping you 🙂

**Comment by Carrie999** [comment]
> I tried placing my images inside absolutely positioned parent containers but it still didn't work, I get no parallax effect at all.
> 
> With parallax disabled, everything is positioned as expected, but when enabling the instance, `top` is reset to 0 and nothing is moving at all.
> 
> ```
> <div id="scene">
>     <div class="slide" id="slide1"><img src="/img/slide1.png" alt="" data-depth="0.6"></div>
>     <div class="slide" id="slide2"><img src="/img/slide2.png" alt="" data-depth="0.6"></div>
>     <div class="slide" id="slide3"><img src="/img/slide1.png" alt="" data-depth="0.6"></div>
> </div>
> ```
> 
> ```sass
> #scene {
>     position: relative;
> 
>     .slide {
>       position: absolute;
> 
>       &#slide1 {
>         top: 50px;
>       }
>   
>       &#slide3 {
>         top: -50px;
>       }
>     }
> }
> ```

thanks
