### ISSUE TITLE
Reversed axis when embedded in an iframe

### ISSUE THREAD

**Issue by Sandstedt** [wagerfield/parallax#231]
Noticed that the axels are inversed when embedding a project in an iframe (and yes, iframes as still in heavily used in example web banners or on sites like Codepen).

For example if you tilt your phone to the right, the elements moves upwards, and when tilting forwards, they move to the right.

Here's a test that's failing on Android Chrome 61 and Safari iOS11:
[https://codepen.io/fullystudios/pen/MEZZPO](https://codepen.io/fullystudios/pen/MEZZPO)
(for the pen to work in Safari, you need to view it in debug mode)

**Comment by Sandstedt** [comment]
Can add that it works in landscape but not in portrait mode (in Android Chrome 61 at least)

**Comment by reneroth** [comment]
Fully agree that there are valid reasons to use iFrames. I will build a simple test case and check out this interesting bug. If it's fixable, I will fix it :) promise 🤞

**Comment by Sandstedt** [comment]
Awsome! Let me know you want some help.

**Comment by reneroth** [comment]
not something that should/will be done in the library, but one could [check for iframe](https://stackoverflow.com/a/326076/2784939) and adjust the parallax settings accordingly to compensate
