### ISSUE TITLE
`destroy()` method is not present on the Parallax instance

### ISSUE THREAD

**Issue by AlexLomm** [wagerfield/parallax#232]
`destroy()` method is not present on the created instance. Is this a bug, or am I missing something?

**Comment by reneroth** [comment]
Which version are you using?

**Comment by AlexLomm** [comment]
The 3.1.0 one

**Comment by reneroth** [comment]
Do you have a live demo I can check out?

I just double-checked using the [demo for the 3.1 release](https://github.com/wagerfield/parallax/releases) and the destroy method is working

**Comment by AlexLomm** [comment]
I see, the error was on my end. 

Thank you :)
