### ISSUE TITLE
Flickering on mobile

### ISSUE THREAD

**Issue by griffiths** [wagerfield/parallax#233]
I'm having an issue where child elements are flickering (looks like opacity or display toggling, potentially?) while panning around the page in Chrome and Safari on iOS. Everything seems to render properly on desktop, so I'm not sure where the issue lies.

Live demo can be found here:
http://rs.brndn.net/

Any advice on how I might go about debugging this?

Thank you for your help!

**Comment by reneroth** [comment]
Sorry for the super-duper-late reply! 😓 

Seeing how the demo page is down, you've either fixed the problem or moved on by now. Either way, if you ever should revisit this project, please feel free to reopen this issue.
