### ISSUE TITLE
Animated gif as layer

### ISSUE THREAD

**Issue by bfalchuk** [wagerfield/parallax#234]
Are there known limitations/caveats re using animated gif as a layer in the parallax? Seems to work fine on Windows 10's Chrome and Edge. However Firefox 57.0 seems to update the animated gif for one iteration but then halts as soon as the parallax moves in any way (i've enabled image.animation_mode to true on FF, w/o luck).

**Comment by reneroth** [comment]
I never tried it before, to be honest. Could you provide me with a simple working demo? Now I'm curious :)

**Comment by bfalchuk** [comment]
Hi - I used Matthew's lib extensively in the 'wow' page of my VJDay prj (link: [https://entervjday.appspot.com/](https://entervjday.appspot.com) ). (I actually would love it if Matthew saw it). On that wow page one of the layers is an animated gif on which a neon sign is flashing. It renders reliably on some browsers but alas, not on all.

**Comment by reneroth** [comment]
reoccuring browser side bug - firefox can do these things okayish as of 2024, but i noticed it's now Safari that has problems with that

nothing we can do inside the library to fix these problems :(
