### ISSUE TITLE
Targeting multiple scenes with new jQuery syntax?

### ISSUE THREAD

**Issue by thedonquixotic** [wagerfield/parallax#237]
According to the updates I've read about version 3, the jQuery plugin has been depreciated. Instead the readme suggests that we use:

```
var scene = $('.target').get(0);
var parallaxInstance = new Parallax(scene);
```

This selects the first div with the target class but it doesn't select any of the others. Am I misunderstanding the limitations of this jQuery syntax?

**Comment by reneroth** [comment]
For creating multiple layers at once, you could loop through all elements, something like this (untested) should work:

```javascript
var targetElements = document.getElementsByClassName('target');
// or, if you insist on using jQuery
var targetElements = $('.target').get();

var scenes = [];
for (var i = 0; i < targetElements.length; i++) {
  scenes.push(new Parallax(targetElements[i]));
}
```
Please let me know if this works out for you! 🙂

**Comment by thedonquixotic** [comment]
It does thank you! 

Jus tso I understand correcty, even with using jQuery it has to loop through the elements correct? Because otherwise it returns an array and parallax.js needs a single target for setting up a scene, correct?

**Comment by reneroth** [comment]
Yes, exactly! Sorry for taking so long to respond 🙈
