### ISSUE TITLE
prevent white edges

### ISSUE THREAD

**Issue by brewster1134** [wagerfield/parallax#238]
if i have a background image that i want to have slight parallax movement on, how can i scale it up so that with the furthest movement in each direction, you would never see beyond the edge of the image?

**Comment by lexleo** [comment]
You can simply scale it with "transform: scale(1.2)" - select value yourself

**Comment by brewster1134** [comment]
is there a way to calculate the exact amount to scale based on the depth/image dimensions?

**Comment by enlightenmental** [comment]
This would be a nice feature to have. +1

**Comment by reneroth** [comment]
That's indeed a nice feature, I'll see about the best way to implement this! Maybe it's a simple calculation one could even perform without adjusting the library? 🤔

**Comment by marikunt** [comment]
YES - this would be a nice feature to have. +1

**Comment by reneroth** [comment]
This will unfortunately not make it into the library, but is imo something that can easily be done with a bit of math. ChatGPT could probably even help here :) you'd need to take the size of the image, the size of the screen, the maximum offset, and calculate a scale from that.
