### ISSUE TITLE
Why I can't set up a <a> tag with this plug-in which is functional?

### ISSUE THREAD

**Issue by choi12191995** [wagerfield/parallax#239]
My code is below:
```
<section class="explore-more" id="about">
                <div class="explore-more-title" data-depth="0.2">CCC???</div>
                <div class="explore-more-content" data-depth="0.4">CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC</div>
                <div class="explore-more-btn" data-depth="0.6" onclick="alert('dwug')"><a href="/en/about/">Explore More</a></div>
                <!-- the parallax I don't know why prevent default event -->
                <div class="explore-more-img"><img src="" alt=""></div>
            </section>
```
```
$(function() {
            new Parallax(document.querySelector(".explore-more"), {
                invertX: false,
                invertY: false,
                limitX: 50
            });
        });
```

The issue is when I click on the ".explore-more-btn", there is no any response. When I mouse over it, also show the default cursor, not the pointer. I hope to make the word "Explore More" move as parallax, and also is a clickable and functional button. Is there any code prevent the default event?

**Comment by jpalmieri** [comment]
I think you'll need to set `pointer-events: all` in the css for the layer which will need to respond to clicks.

More info here: https://github.com/wagerfield/parallax#pointerevents

**Comment by reneroth** [comment]
Yup, pointer events are a bit tricky with this. The simplest possible solution would be
```css
.explore-more-btn a {
  pointer-events: all;
}
```

Please feel free to reopen this issue if it did not solve your problem.
