### ISSUE TITLE
Is it possible to selectively magnify the effect of the gyroscope parallax?

### ISSUE THREAD

**Issue by thedonquixotic** [wagerfield/parallax#240]
I have put very very subtle parallax on my website using parallax.js 

It works quite well for the mouse/desktop mode but I find the data-depth settings to be a tad too low for when it's running on mobile/gyroscope. 

Is there a variable that I could set or access to magnify the gyroscope driven parallax? So that on desktop it would be set to data-depth= .1 and react as such, but then on mobile would have a data-depth setting of .1 but react as if it were set to .4 ?

**Comment by reneroth** [comment]
For this you can programmatically set the [scalar values](https://github.com/wagerfield/parallax#scalarx--scalary) of the instance at runtime. Please feel free to reopen this issue if there is anything else you need help with!

**Comment by thedonquixotic** [comment]
Thanks!
