### ISSUE TITLE
destroy() does not work if element was called before.

### ISSUE THREAD

**Issue by komarovartem** [wagerfield/parallax#241]
Hi, not sure if this is an issue but in an example where you need to activate and destroy the scene by buttons and without glob variables, destroy method works odd. It removes style from the scene but child elements still responding to cursor move. Made a pen to show the issue https://codepen.io/komarovdesign/pen/NXpVyZ

**Comment by reneroth** [comment]
Sorry for the late reply, the new year caught me by surprise!

You're creating a new scene instance and destroying it instead of destroying the old instance in your code example:

```javascript
document.getElementById('activateme').onclick = function() {
  var scene = document.getElementById('scene');
  var parallax = new Parallax(scene); // this creates a new instance, stored in a variable that is only available in this function
};

document.getElementById('deleteme').onclick = function() {
  var scene = document.getElementById('scene');
  var parallax = new Parallax(scene); // this creates a new instance too, instead of retrieving the old one, again only valid in this scope
  parallax.destroy(); // this destroys the new instance
  parallax = null;    
};
```

You might want to read up on the basics of [scope in JavaScript](https://stackoverflow.com/a/500459/2784939).

Do it like this instead:
```javascript
var parallax;
document.getElementById('activateme').onclick = function() {
  var scene = document.getElementById('scene');
  parallax = new Parallax(scene);
};

document.getElementById('deleteme').onclick = function() {
  parallax.destroy();
  parallax = null;    
};
```

Please feel free to open another issue if there's anything else you need help with!

**Comment by komarovartem** [comment]
Hello, thanks for a reply but I mentioned that it needs to be done without glob variables.

**Comment by reneroth** [comment]
You will need some way to store and access the instance, it can't work the way it's done in your demo.

Without fulling knowing about and understanding the limitations of your project, the only other solution I can come up with right now would involve you creating a fork of the parallax library and implement a static method to retrieve created instances, either from storage or by element.
