### ISSUE TITLE
Make css top and left

### ISSUE THREAD

**Issue by Alissonk** [wagerfield/parallax#242]
Hello, I would like to know how to set the css of the elements in the scene, because the plugin overlaps the top and the left in the css ...

**Comment by liquidvisual** [comment]
I don't like how the plugin does this, in many of my use cases I need to set my own top and left but the opinionated styles override everything.

**Comment by reneroth** [comment]
position the child elements of the layers instead

**Comment by halnex** [comment]
> For reference, you need to wrap your layer in a positionable element like this :
> 
> ```
> <div id="parallax">
> 	<div  id="myabsoluteelement"><div class="layer"></div></div>
> </div>
> ```
> Then use `selector : '.layer'` on parallax init.

I can confirm, this works like a charm.

**Comment by patternica** [comment]
You simply can use "!important" for your top and left values. Then it will deactivate values from the lib.
{code}
top: 50% !important;
left: 50% !important;
{code}

**Comment by LucaRosaldi** [comment]
Inline styles are a major pain in the butt. Call me a purist, but I feel **bad** every time I have to override a style with !important.

I ultimately forked the library and removed the javascript which set the inline styles.
Now I cannot update the library, though. 😢 

It would be great to at least have an option to disable inline styles.
