### ISSUE TITLE
Calling Parallax on element - parallax_js_1.default is not a constructor

### ISSUE THREAD

**Issue by Sartor87** [wagerfield/parallax#244]
I am trying to integrate the library with the SharePoint Framework's Application Customizer - it is an out of the box customizer (https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions)

The element is successfully created in the dom, the library is properly referenced in the typescript file, but once I call it, it throws an error:

Uncaught TypeError: parallax_js_1.default is not a constructor

By using step-in debug, it did not get into the constructor of the module (parallax.js is loaded in the browser).

I've tried to reference the library with:
import Parallax from 'parallax-js' AND then
const Parallax = require('parallax-js')

Any hints what could be done?

**Comment by oxiumio** [comment]
Do the import as follows:
`import * as Parallax from 'parallax-js';`

importing as shown in documentation did not work for me
