### ISSUE TITLE
Different invertX & invertY for each layer

### ISSUE THREAD

**Issue by wbogaert0** [wagerfield/parallax#246]
Hello,

Is it possible to let different parallax layers move in different x / y directions? 
For example, when the mouse goes to the right, "foreground.png" goes to the right and "background.png" goes to the left.

I've tried something like this, but to no avail:

```
<div data-depth="0.1" data-invert-x="false">
<img src="foreground.png">
</div>

```
I'm just a beginner in javascript, but I would really appreciate if you could give me some feedback on this!

Thank you for your response!

**Comment by reneroth** [comment]
Check out this example: https://github.com/wagerfield/parallax/blob/master/examples/pages/separate_axis_data.html

**Comment by wbogaert0** [comment]
So obvious! Thank you!
