### ISSUE TITLE
react

### ISSUE THREAD

**Issue by VintageVoodoo13** [wagerfield/parallax#251]
could you guys give an example of how the code would look in React?

**Comment by TheDoubt** [comment]
this example is work for me. [https://github.com/wagerfield/parallax/issues/167](url)

**Comment by majidzeno** [comment]
@VintageVoodoo13 @TheDoubt #167 Works for me but also check my answer, the new update of React 16.3 recommend using refs by `React.createRef()` API [here](https://reactjs.org/docs/refs-and-the-dom.html)
