### ISSUE TITLE
chrome console has [Deprecation] warning

### ISSUE THREAD

**Issue by iamike** [wagerfield/parallax#252]
Recently, if you are using latest chrome, you may find annoying warning.

[Deprecation] The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

is that mean, we will only support it when HTTPS is enabled.

**Comment by reneroth** [comment]
Yes, time to switch to HTTPS - you should do so anyway :)
