### ISSUE TITLE
More content on page than parallax container

### ISSUE THREAD

**Issue by rodolforamos** [wagerfield/parallax#255]
I have the container working great with parallax. But when I try to put other contents below the parallax's container they simply do not show. The parallax treat every thing as container child element, so the page cannot be scrolled down to see other elements.

The element "section" is being put inside the "scene" content as a parallax child.

	
	<div class="container">
		<div id="scene"
			data-calibrate-x="false"
		  	data-calibrate-y="true"
			data-invert-x="false"
			data-invert-y="true"
			data-limit-x="100"
			data-limit-y="100"
			data-origin-x="1"
			data-origin-y="1">

				<div class="back" data-depth="0"></div>
				<div class="piramideAlinhamento logo" data-depth="1.2"></div>
				<div class="piramideAlinhamento piramide3" data-depth="1.0"></div>
				<div class="piramideAlinhamento piramide2" data-depth="0.8"></div>
				<div class="piramideAlinhamento piramide" data-depth="0.6"></div>
				<div class="piramideAlinhamento base" data-depth="0.4"></div>
			
		</div>
	<div>
	

	
	<section class="contents" id="aboutUs">
		fsdfdsfdsfds
		<h1>ifjdsijfsd</h1>
		<h1>ifjdsijfsd</h1>
	</section>

What I'm missing??
Thanks in advance. 

Cheers from Brazil.

**Comment by reneroth** [comment]
```
<div>
<!-- /land screen -->
```

You are not closing the div correctly, instead opening another one. I suggest switching to an IDE that makes spotting errors like those easy on you :)
