### ISSUE TITLE
New User: Issue with another script action

### ISSUE THREAD

**Issue by Deelite310** [wagerfield/parallax#256]
I have two images that I'm using a click function on, but is "negated" when I put them within the <scene> tag. Basically if you click on one of the two image, it scrolls down to another section on the page. when I add in the var for Parallax.js , the script for these two images no longer work.

Jquery; this is the code I'm using on the two images with id's assigned to them:

`$("#box, #arrow").click(function () {
			$("html, body").animate({
				scrollTop: $("#section").offset().top}, 'slow');
		});`

what am I doing wrong?

**Comment by reneroth** [comment]
Did you check the info on `pointerEvents` in the Readme? :) If it still does not work, please provide me with a minimal demo so I can check the code out myself.

**Comment by Deelite310** [comment]
How do I use them? I see no examples.

**Comment by reneroth** [comment]
[Section 2](https://github.com/wagerfield/parallax#21-programmatic-vs-declarative) of the Readme deals with configuration.

Or check out the [code example for interactive layers](https://github.com/wagerfield/parallax/blob/master/examples/pages/interactive.html)

**Comment by Deelite310** [comment]
thank you but how do I use them? example please.

**Comment by reneroth** [comment]
Sorry, I am not sure how else to help you. You have the documentation and the code examples, if there is anything else I could provide to you, please let me know.

**Comment by Deelite310** [comment]
Like where in the code? all I have is 

` var scene = document.getElementById('scene');
  var parallax = new Parallax(scene);`


Where do I put the pointer events?

**Comment by reneroth** [comment]
As it says in the JS comment, you will also need to check the CSS. Quoting the Readme:

> Set to true to enable interactions with the scene and layer elements. When set to the default of false, the CSS attribute pointer-events: none will be applied for performance reasons.
> Setting this to true alone will not be enough to fully interact with all layers, since they will be overlapping. You have to either set position: absolute on all layer child elements, or keep pointerEvents at false and set pointer-events: all for the interactable elements only.

Depending on your setup, it might be as simple as doing
```
.custom-button {
  pointer-events: all;
}
```
