### ISSUE TITLE
Can't Make hoverOnly Work

### ISSUE THREAD

**Issue by iAskStupidQuestions** [wagerfield/parallax#259]
Hello,

 I'm trying to prevent the parallax effects working when user is not hovering over the target div. But when I look at the developer tools, I can see that the elements still moves.

```
document.addEventListener('DOMContentLoaded', () => {
    var parallaxInstance = new Parallax(scene, {
        relativeInput: true,
        hoverOnly: true
    });
}, false)
```

**Comment by yashb319** [comment]
please give the related code buddy
