### ISSUE TITLE
pllarax in vue.js

### ISSUE THREAD

**Issue by joseAveleira** [wagerfield/parallax#264]
how is it used in vue.js? a small example
In my attempts I use
Vue.use (Parallax)
but I get the error when I call it in a component
var parallaxInstance = new Parallax (scene)
that 'Parallax' is not defined
Thanks in advanc

**Comment by reneroth** [comment]
You do not need `Vue.use`. Import it in the component where you use it.

**Comment by joseAveleira** [comment]
Thank you!
solved my problem
