### ISSUE TITLE
Parallax with gyroscope not working on mobile

### ISSUE THREAD

**Issue by tiagocrt** [wagerfield/parallax#268]
I'm trying to use the parallax effect and it works fine with mouse moviment. But on mobile the parallax effect with gyroscope is not working. But the thouch effect works thou. 
Tested in google Chrome (android) and Safari (iOS).

Link to the project exemple - http://virtualize.no-ip.org:8088/scifi

I'm using the minimal setup:
var scene1 = document.getElementById('scene1');
var parallaxInstance = new Parallax(scene1);

**Comment by calarca** [comment]
I have the exact same issue. Few days ago my code was working fine on mobile, but now is not and I haven't change anything. 
Also when enter to []([http://matthew.wagerfield.com/parallax/] ) it works only when I touch the screen.

**Comment by edueter** [comment]
> I have the exact same issue. Few days ago my code was working fine on mobile, but now is not and I haven't change anything.
> Also when enter to http://matthew.wagerfield.com/parallax/ it works only when I touch the screen.

Same here, partially. On Android systems it seems to be true, but on iOS everything is seems ok for now.

**Comment by ilbuonteo** [comment]
I have the exact same issue. Still no news?

**Comment by ArturJD** [comment]
Actually, this is not a issue. To use hardware resources through the browser, you need a domain secure with SSL.

If you are using a **local** environment use [ngrok](https://ngrok.com) to create a tunnel and then go to the path created with `https`

e.g:
https://qwert1234.ngrok.io

**Comment by ArturGuedes** [comment]
Actually, this is not a issue. To use hardware resources through the browser, you need a domain secure with SSL.

If you are using a local environment use ngrok to create a tunnel and then go to the path created with https

e.g:
https://qwert1234.ngrok.io

**Comment by etiennedupuis** [comment]
Same problem here. Quite frustrating because it specifically says it works with mobile on the homepage: [...] parallax.js reacts to the orientation of your smart device, offsetting layers depending on their depth within a scene... [...]

**Comment by reneroth** [comment]
I'll provide you with a full refund if this proves too frustrating 🙂 

There are two problems at play right now:
- gyroscope data is only available on SSL
- recent iOS versions moved the permissions for Safari accelerometer into the Settings app

Nothing I can do about this except update this repo's Readme, as I don't have access to the showcase homepage.

**Comment by zandergrin** [comment]
@reneroth as you can't update the showcase - is there a working demo somewhere?

Thanks!

**Comment by kirkone** [comment]
> @reneroth as you can't update the showcase - is there a working demo somewhere?
> 
> Thanks!

just add a `s` to the url:
https://matthew.wagerfield.com/parallax/
As mentioned above this will only work for https pages

**Comment by SkyWriter** [comment]
https://matthew.wagerfield.com/parallax/ no luck on iOS 13.5.1 iPhone X. Neither Chrome, nor Safari uses the gyro.

**Comment by DavidBruchmann** [comment]
gyroscope has to be enabled by the user:
https://vrprotour.com/how-to-make-webvr-and-gyroscope-work-on-safari-in-ios-12-2/

**Comment by reneroth** [comment]
added to readme
