### ISSUE TITLE
Uncaught ReferenceError: Parallax is not defined

### ISSUE THREAD

**Issue by Hellobast** [wagerfield/parallax#270]
Hi, 

When i load simple.html, i've a error after "Parallax(scene)" 
Can you help me please ? 

Bastien

![Capture d’écran 2019-06-27 à 19 07 31](https://user-images.githubusercontent.com/45485272/60285924-f0335a80-990e-11e9-8f04-46ec1c09c344.png)

**Comment by ParaCSS** [comment]
I get this error as well. Can someone help?
