### ISSUE TITLE
Fatal error on ios when zooming page

### ISSUE THREAD

**Issue by kusa-work** [wagerfield/parallax#272]
When zooming page with parallax in ios safari, occurring crash of page
It definitely happens on:

- iPhone XS Max
- ios 12.3.1

and

- iPhone X
- ios 12.4

Screenshots and video:
https://drive.google.com/uc?id=1cZVS7liW3oTJuhaYXxmyGH9UHQwE-PyF
https://drive.google.com/uc?id=1wT3BDR665KmAayys-ulhWEX6bvdwjDM1
https://drive.google.com/uc?id=1o2Blyn8B6_2iyQVMcm5wRjXfXEcAADYW

**Comment by reneroth** [comment]
apple side issue, but hopefully fixed by now
