### ISSUE TITLE
It dosen`t work

### ISSUE THREAD

**Issue by Mohammadreza-73** [wagerfield/parallax#276]
I try to use, but it doesn`t work

**Comment by reneroth** [comment]
I am sorry to hear that friend

**Comment by gerardnico** [comment]
The examples are working:
https://github.com/wagerfield/parallax/blob/master/examples/pages/

**Comment by nmartin42** [comment]
> I try to use, but it doesn`t work

Please try providing more details so people can assist you. Share code, share the environment you're working in, how are you implementing it, etc.
I've used Parallax for numerous projects and have had no issues.
