### ISSUE TITLE
Using Parallax for the background

### ISSUE THREAD

**Issue by Bradass-Mofo** [wagerfield/parallax#277]
Mt friend and I are working on making a website for a school project and I wanted to add mouse parallax. I am very new to HTML and CSS and we can't figure our how to make it so just the background has parallax and it sits behind everything else.
[Indexhtml.zip](https://github.com/wagerfield/parallax/files/3823094/Indexhtml.zip)

**Comment by Bradass-Mofo** [comment]
It is kind of a gross mess right know because we have just been messing with stuff to try to get it to work.

**Comment by reneroth** [comment]
The easiest way would be to add a wrapper to the scene element (in this case the `div` containing the `ul#scene`) and positioning it fixed and in the background:

```css
    position: fixed;
    top: 0;
    right: 0;
    left: 0;
    bottom: 0;
    z-index: -1;
```

**Comment by Bradass-Mofo** [comment]
Thank you so much, you do not want to know how much time we spent on just getting this part done.
