### ISSUE TITLE
How to make it receive the values of how much you've scrolled (vertical and horizontal) instead of cursor coordinates and have it act on scroll instead of on mouse move

### ISSUE THREAD

**Issue by MadalenaSousa** [wagerfield/parallax#280]
Hi! First of all thank you for making this code public, great work!

I was trying to use it on my university project and I was wondering how to make it receive the values of how much you've scrolled (vertical and horizontal) instead of cursor coordinates and have it act on scroll instead of on mouse move.

Any help would be good! Thank you!

**Comment by cyanerd** [comment]
@MadalenaSousa, hello! have u find any solution? thanks

**Comment by reneroth** [comment]
not possible by default, code could be forked to do this, but I would use a different library like [skrollr](https://prinzhorn.github.io/skrollr/) or [scrollmagic](https://scrollmagic.io/) for that
