### ISSUE TITLE
It Does Not Reacts to the Orientation of my Android Phone

### ISSUE THREAD

**Issue by NgYueHong** [wagerfield/parallax#282]
Hi,

I tried visiting to http://matthew.wagerfield.com/parallax/ using my Android 7.1 phone on up to date Google Chrome browser, but the scene does not react to the orientation of my phone at all.

**Comment by maciejcieslik** [comment]
Same here - script do not work on mobile device (at least on android)

**Comment by xjure** [comment]
It doesn't work on iOS either. Neither on Chrome or Safari.

**Comment by DavidBruchmann** [comment]
Device orientation has to be enabled by the user.  
https://help.momento360.com/article/34-vr-icon-isnt-showing-in-mobile-safari-ios

**Comment by wil93** [comment]
This demo page works: https://mdn.mozillademos.org/en-US/docs/Web/API/Detecting_device_orientation$samples/Orientation_example

The page mentioned in the first comment here, does not.

(I'm using the same Chrome browser for both URLs)

**Comment by reneroth** [comment]
added to readme
