### ISSUE TITLE
Using parallax with custom transform styles

### ISSUE THREAD

**Issue by lukisrac** [wagerfield/parallax#289]
Hi,

is there any way to use custom CSS transform properties with parallax library?

I need to use `transform: rotate()` property on each element in scene, but after parallax init, it removes my `transform: rotate()` from all layers.

I appreciate any help, and sorry for my bad English :(
Thank you!

**Comment by Stian-Scholtz** [comment]
Hi. I too have elements with transformation that do not persist. As soon as the Parallax instance instantiates, the transformation applied via css are removed. Anyway we can take into account the existing styles?

**Comment by durchanek** [comment]
An easy workaround is to add an extra HTML element and apply your custom styles on it.

**Comment by x4r7** [comment]
you should wrap the images with position and transform inside the div wrapper with 100% width
then it will work ok
