### ISSUE TITLE
How to move element autometically like parallax js github page?

### ISSUE THREAD

**Issue by asif-jalil** [wagerfield/parallax#290]
I want elements will move automatically after page load like [https://matthew.wagerfield.com/parallax/](https://matthew.wagerfield.com/parallax/). How to do that? Is it possible with parallax js or need any other plugin?

**Comment by yuda85** [comment]
You can use CSS animations to do that, just make sure you do not interfere with the rules provided by the library e.g position, transform, etc.

**Comment by reneroth** [comment]
That's separate CSS animations applied inside the parallax layers themselves - important, not _to_ the layers :)
