### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by dancs2520** [wagerfield/parallax#291]
Hey there,
I am trying to use parallax.js with the downloaded files but I just can't make it work.

Browser returns: "Uncaught ReferenceError: require is not defined at parallax.js:9"
What does it mean? Does anyone know what I am doing wrong?

It somehow works fine if I use the CDN, but it would be preferable to my project to use local files.
Thanks

**Comment by michaelichiro** [comment]
I am a old user of this plugin. I still using a very old version.
Today i try to use the new version, i download the version 3.1 file from there, i cannot make it work too.

After a few hours, i try another file from:
[https://cdnjs.com/libraries/parallax](https://cdnjs.com/libraries/parallax)

the parallax.min.js on this site is working fine.
May be the file on github have some bugs......? It waste me few hours.....

**Comment by reneroth** [comment]
You should both read the Readme file and then come back with a more detailed error report. Most likely you're both not using the provided precompiled files.

**Comment by dancs2520** [comment]
@reneroth , I have downloaded again the compiled zip file and you were right, it works now.. I really don't know where did I get the files I were using, I was pretty sure to have downloaded it from the same place I did now... I hope my friend @michaelichiro will make it work too. Thanks a lot for the help!
