### ISSUE TITLE
Paralaxa not workin on smarthone or mobile

### ISSUE THREAD

**Issue by lukaszkurowskilbn** [wagerfield/parallax#304]
Hello,

I don't know why, but parallax does not work on mobile devices, I tried to diagnose it, but I don't know where to look
https://prezentacje.beeq.pl/para/html/index.html

**Comment by hypericon** [comment]
There's a warning I just found on Safari Mobile:

`No device motion or orientation events will be fired until permission has been requested and granted.`

maybe there's something more they can do to fix this?
or prolly there's no longer change due to safari restrictions..

**Comment by DavidBruchmann** [comment]
nothing new:  
https://github.com/wagerfield/parallax/search?q=safari&type=issues

**Comment by poisonborz** [comment]
An important thing, I think this should be visibly highlighted in documentation: **most Android browsers I tested do not expose gyro API to non-https pages.**

**Comment by reneroth** [comment]
Added information to readme
