### ISSUE TITLE
found bugfix for mediastream handling

### ISSUE THREAD

**Issue by photochamber** [wagerfield/parallax#306]
I tried this library and it didnt work. I found that the browsers have changed thier mediastream handling. in headtrackr.js, line 171 and below you need to change it to 
```
 headtrackerStatus("camera found");
-->   video.srcObject = stream;
video.play();
```
tested in Chrome and FF. Tried to make a PR but repo seems to archived?

**Comment by reneroth** [comment]
Hey friend, I believe you are lost and posting to the wrong repo :)
