### ISSUE TITLE
Parallax layer flickering on mobile landscape mode

### ISSUE THREAD

**Issue by ivanblank992** [wagerfield/parallax#311]
Hi there,

I am using this package which is great. On desktop works nice, but on a mobile device(landscape) when I touch screen some layers are flickering, also when using the gyroscope. I am developing a fullscreen landing page using parallax so I need x and y movements. Also, is there any way to zoom out any of the layers So I do not need to use transform scale? Thank you in advance

**Comment by reneroth** [comment]
To add custom transforms to layers (e.g. zoom out), you'd need to wrap the contents of that layer into another wrapping div to which you apply the transforms, because the library itself is applying transforms to each layer.

Closing this issue because old + no demo
