### ISSUE TITLE
Does not work with Angular Universal 

### ISSUE THREAD

**Issue by Liudmyla01** [wagerfield/parallax#316]
Hello! I'm using Angular Universal (SSR) for SEO and after compiling have a problem (server build) :
ERROR TypeError: Cannot read properties of null (reading 'indexOf')
<img width="1198" alt="167590141-62be6578-1bda-4c10-8b90-0b34cbc87f20" src="https://user-images.githubusercontent.com/74067187/167887442-c44f4d81-5163-465c-9548-79be8909b589.png">

**Comment by reneroth** [comment]
I think the problem here is the server side rendering, since in the SSR context, you might not have access to some browser specific methods and objects. There should be a way to exclude the parallax library from SSR.
