### ISSUE TITLE
Uncaught ReferenceError: Parallax is not defined

### ISSUE THREAD

**Issue by harnishdesign** [wagerfield/parallax#320]
I have used parallax in home page and it is working fine. but, Does get error as below in console for other inner pages.

![screnshote](https://user-images.githubusercontent.com/2634085/189115455-f5cc2530-c143-46a2-baaa-3913c0383296.jpg)

**theme.js file.**
```
window.onload = function () { 
	var scene = document.getElementById('scene');
	var parallaxInstance = new Parallax(scene);
}
```

**Comment by reneroth** [comment]
The library javascript file is not included in the page you're getting this error, but only on the home page, it seems.
