### ISSUE TITLE
Img starting position

### ISSUE THREAD

**Issue by AleksandarNeustadt** [wagerfield/parallax#321]
I have 3 transparent superhero image, and i want that all start form center. But, ... only one is in center, and other on position 0,0 

how to solv that, dat all 3, other all X number of image, start from vertical and horisontal center ?

**Comment by reneroth** [comment]
If you didn't solve it by now and it's still relevant (sorry late reply), please reopen with demo code. It sounds more like a CSS issue and less like a bug with the library :)
