### ISSUE TITLE
Request to add a clock, date and weather text

### ISSUE THREAD

**Issue by HorrySheet11** [wagerfield/parallax#325]
Hello, im new here and I love this wallpaper that want to make a request.
I wanna ask if it is possible to add a clock, date and weather text on this awesome wallpaper and be on the side maybe just like this live wallpaper made by rocksdanister

https://www.deviantart.com/rocksdanister/art/The-Great-Wave-850391980
![image_2023-08-06_224751152](https://github.com/wagerfield/parallax/assets/112994197/081b39c7-3edf-4bd1-b1d7-f1f075f2e479)

I was thinking of the wallpaper being like this:
![Untitled](https://github.com/wagerfield/parallax/assets/112994197/2ebf5f5f-ce1b-4b32-a478-d860c9c3338e)
(dont mind the white background, i was trying to illustrate my idea with paint:))
If it is not possible then it is fine by me but if it is possible then I would be glad to use it as my wallpaper.(Also changing the font color to be readable and match the theme would be nice, the font style is fine.)

**Comment by DavidBruchmann** [comment]
It certainly should be possible.  
What hinders you to work on it?

**Comment by vnova** [comment]
A lot of possibilities exist for error-prone and accurate code. It is unclear as to what the prevention here may be for user# [HorrySheet11](https://github.com/HorrySheet11)

**Comment by DavidBruchmann** [comment]
A clear HTML structure that separates parallax code and static elements might be a good advise.  
So the watch is dynamic but doesn't move by parallax effect, so it should be placed in the section with static elements.  
It's a very basic advise, so perhaps that's already clear anyway.  
For functional and design related questions concerning the watch here is certainly the wrong place, but it can be handled completely independent. According questions should be addressed to some general DHTML forum if required.

**Comment by vnova** [comment]
Is this MAC or PC? Are you (op) perhaps trying to simulate that font on a pre-existing computer function of adding a current time to a desktop wallpaper? Also, is your wallpaper going to change or animate in any way to resemble am vs pm or do you always want it to display the same time and date? If so, static is your best option.

**Comment by HorrySheet11** [comment]
Hello, thanks for responding to my request! I am not a professional programmer so i do not know how to code these type of stuff. I'm just a user and sort of a newbie in programming but I do have a basis and some understanding on what you guys are explaining. I use PC. Just adding the clock, date, and weather as a static text is fine. The am and pm thing affecting the wallpaper is no need. Just the normal clock, date, and weather on the side.

**Comment by DavidBruchmann** [comment]
put it as competition on freelancer.com, then you get way cheap, even with choice between several solutions.

**Comment by HorrySheet11** [comment]
Ok, thank you very much!

**Comment by reneroth** [comment]
Thanks for the help @DavidBruchmann  :) closing for now, as it's out of scope for the purpose of this library.
