### ISSUE TITLE
Bug! this repos home page shows up in desktop

### ISSUE THREAD

**Issue by fzsf163** [wagerfield/parallax#327]
I don't how it happened. But this repos home page replaced my desktop wallpaper which was parallax js.  I could click on the links but when I did it all went black.

This is how it looks. Image is little cropped due to privacy.

![Screenshot 2023-12-21 014416](https://github.com/wagerfield/parallax/assets/86884235/5edd901f-38be-43c5-8402-a9b2a9148b94)

This became my wallpaper. Hidden items are my stuffs on desktop.

**Comment by reneroth** [comment]
lol

**Comment by reneroth** [comment]
what did you use to set up the background homepage? maybe the URL changed? this website is the code for the effect you see on https://matthew.wagerfield.com/parallax/ - maybe set the background to that URL?

**Comment by fzsf163** [comment]
> what did you use to set up the background homepage? maybe the URL changed? this website is the code for the effect you see on https://matthew.wagerfield.com/parallax/ - maybe set the background to that URL?

I used lively wallpaper from windows store. It was working fine. Then suddenly In front of eye everything went black and boom git repo.

**Comment by reneroth** [comment]
A bit of an explainer - the website https://matthew.wagerfield.com/parallax/ is a demonstration of the code in this repository.  
It seems likely that there were accidental mouse clicks on the ℹ️  button on that demonstration page, and then on the Github link, which links to this repository :)

**Comment by fzsf163** [comment]
Thank you for clarifying.
