### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by DrMabuse23** [wagerfield/parallax#67]
Hi Thx for your great lib.

on question about bower how to get the version 2.0.1 ?

i get this 

```
bower update
bower parallax#~1.1.1           cached git://github.com/wagerfield/parallax.git#1.1.1
bower parallax#~1.1.1         validate 1.1.1 against git://github.com/wagerfield/parallax.git#~1.1.1
```

**Comment by binarykiwi** [comment]
Hi.
I just wanna let you know that `bower i parallax` still installs version **2.1.3** and not the current **3.1.0**.
If I try `bower i https://github.com/wagerfield/parallax.git#3.1.0` I get the message:

> Available versions in https://github.com/wagerfield/parallax.git: 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.1, 2.0.0, 1.1.1, 1.1.0, 1.0.0

**Comment by kukac7** [comment]
@binarykiwi `bower i https://github.com/wagerfield/parallax.git#v3.1` or `bower i https://github.com/wagerfield/parallax.git#master`

**Comment by reneroth** [comment]
I consider bower deprecated (and [the bower team does so too](https://github.com/bower/bower/issues/2298)), so I'm not interested in updating.
