### ISSUE TITLE
Parallax not initializing on Mobile/Tablet devices

### ISSUE THREAD

**Issue by im56seann** [wagerfield/parallax#76]
Having some issues with the parallax function getting fired on mobile devices. Works fine on desktops. The site I'm working on can be found at www.immersioncreative.com/clients/naikoon. It's a bit of a weird issue but here it goes:

When you first view the page on a mobile device (tested on iPod Touch 5, iPad [not sure version, tested by a friend] and iPhone 5) the parallax function does not fire resulting in a static page, no movement. If I then go to your demo (http://matthew.wagerfield.com/parallax/), the demo sometimes starts working on first try, sometimes needs a refresh. Once working there I can go back to my site and everything works fine. I know, super weird. I've compared the two pages and I can't see any differences in the way I'm implementing the code (using jQuery).

There is an old closed issue (onDeviceOrientation won't get fired after restart of mobile safari. #23) which seems very similar to the problem I am having but that guy seemed to disappear after posting and the issue was never resolved. Any ideas?

**Comment by monteirocode** [comment]
I've the same problem iPhone 5s, iOS 9.3.1. I had to bump `supportDelay` to `2000` to fix it. Should it not be made the default value?
