### ISSUE TITLE
iOS home screen bookmarks - layers are not moving

### ISSUE THREAD

**Issue by iShiblee** [wagerfield/parallax#77]
The plugin works great in desktop and Mobile Safari. However, when opening the page from Chrome for iOS or from the home screen bookmark, the layers don't move i.e. translate3d(0,0,0). It looks like it initializes, but does not translate.

I have attached `deviceorientation` and `devicemotion` events and they seem to be giving the correct output when the device moves.

**Comment by RRorg** [comment]
should be fixed in #e1f21b37da7df9d155a14a0a81d30cee1a8b1697

please open a new issue if problems on iOS persist
