### ISSUE TITLE
Raster image layer blurry on Webkit browsers

### ISSUE THREAD

**Issue by arktoga** [wagerfield/parallax#78]
Hello everyone. I'm using the script to animate several layers, each of which is composed by a raster image. Unfortunately, these images appear noticeably blurry on Webkit browsers. Reckoning this may have something to do with Webkit rendering, I tried to give the following properties to both layers and container (   -webkit-backface-visibility: hidden;    -webkit-transform: translateZ(0) scale(1.0, 1.0); ), to no avail. 

Is there any way fix to this?

**Comment by RRorg** [comment]
#736e92d has added an option to round the position values. Please reopen this issue if problems persist.
