### ISSUE TITLE
parallax.updateLayers(); not updating layer motion after setting new data-depth

### ISSUE THREAD

**Issue by kristfal** [wagerfield/parallax#79]
Hey,

first of all. Really awesome plugin, love the simplicity and possibilities it is creating.

Situation:
I'm developing a simple web-based game. The game consists of three individual parallax scenes.

HTML:
<pre><code>

ul id="intro-slide-scene"

...Parallax layers...

/ul

ul id="game-scene"

...Parallax layers...then layer in question that I want to update:

li class="layer" id="elias-layer-changer" data-depth="0.25"
    <div>Foo</div>
/li

/ul

..then another parallax scene
</pre></code>

JS excerpt for initializing game-scene, updating data-depth and update layer:

<pre><code>
var $scene = $('#game-scene').parallax();
$scene.parallax('enable');
$scene.parallax('scalar', 3, 2);
$scene.parallax('limit', 70, 70);

$('#elias-layer-changer').attr( 'data-depth', '2' );
$scene.parallax('updateLayers');
</pre></code>

Confirming that data depth is updated. All other jQuery APIs are working fine, but the layer in question does not see any change of calculated motion after running $scene.parallax('updateLayers');. In other words: it is still running as if the data-depth was 0.25. 

Running the data depth change before the scene variable is declared ( var $scene = $('#scene').parallax(); ) gives the li object the proper calculated motions. 

Disabling and Enabling the scene after updating data-depth does not either change the calculated motion.

Also tested disabling the other scenes.

Am I misinterpreting the API, or is there any other way to update layer-depth in a running scene?

**Comment by dpcdpc11** [comment]
Found the problem and the solution!
The problem is in the updateLayers function.
The solution is this to replace .data('depth') with .attr('data-depth') in the // Cache Depths section of the function. Here's the fixed updateLayers function:

```
  Plugin.prototype.updateLayers = function() {

    // Cache Layer Elements
    this.$layers = this.$context.find('.layer');
    this.depths = [];

    // Configure Layer Styles
    this.$layers.css({
      position:'absolute',
      display:'block',
      left: 0,
      top: 0
    });
    this.$layers.first().css({
      position:'relative'
    });

    // Hardware Accelerate Layers
    this.accelerate(this.$layers);

    // Cache Depths
    this.$layers.each($.proxy(function(index, element) {
      this.depths.push($(element).attr('data-depth') || 0);
    }, this));
  };
```

Now you can use 
```$scene.parallax('updateLayers');```
after changing the depth of the layers and the layout will get updated.

Hope this helps!
