### ISSUE TITLE
Not possible to call disable() right after init

### ISSUE THREAD

**Issue by robbue** [wagerfield/parallax#83]
It's not possible to call disable() right after Parallax is initiated.

Take a look at this demo: http://codepen.io/robbue/pen/5fb2e5b2b00483403675509674d59f55?editors=001

With a setTimeout its possible, but should there be a ready callback or something?

**Comment by RRorg** [comment]
I'll keep this issue open and try adding a ready state callback for version 3.0

**Comment by an-tex** [comment]
As a workaround you can pass {limitX: 0, limitY: 0} as initialization parameters, this effectively disable parallax. then you can remove them later on again

**Comment by didacus** [comment]
Has this been implemented?

**Comment by RRorg** [comment]
I've added an `onReady` parameter, but the solution by @an-text should work too! Please reopen this issue if anything is still unclear or not working correctly.
