### ISSUE TITLE
Relative example doesn't work?

### ISSUE THREAD

**Issue by X-O** [wagerfield/parallax#85]
What should the relative example show:
http://wagerfield.github.io/parallax/examples/relative.html

Shouldn't the parallax stop working when moving the mouse outside the dashed outline with clipRelativeInput checked?

**Comment by mmikkel** [comment]
+1

**Comment by andmitsch** [comment]
+1

**Comment by markoliverbrawn** [comment]
Is this likely to be fixed?

**Comment by Grsmto** [comment]
@markoliverbrawn project hasn't been updated for 2 years. If you want to have this fix you can download the lib from my fork: https://github.com/Grsmto/parallax

**Comment by markoliverbrawn** [comment]
That's what I thought, but just thought I'd check. Cheers.

**Comment by RenanBrenio** [comment]
@Grsmto Thank you for the solution! Really helped me!

**Comment by RRorg** [comment]
It's intended behaviour, not a bug. I can see where you're coming from, but that's not the goal of this library.

I'll keep this issue open and think about having this as an optional mode in v3

**Comment by RRorg** [comment]
this has been added as the parameter `hoverOnly`. Please reopen this issue if anything is not working as expected :)
