### ISSUE TITLE
Inside iframe

### ISSUE THREAD

**Issue by pattan** [wagerfield/parallax#86]
Hello.
If you try to run parallax in an iframe. Eg for an ad or similar and experience strange behavior with the gyro. 

Things I've discovered if you are on a mobile / tablet. 
- 'onWindowResize' will never run. Iframe's dimensions is fixed (normally) even if the parent window has changed. (Turning the unit) 
- This leads to parallax never know if we are in portrait / landscape mode. 

To fix this is easy. Check if we are in a frame, if so, use window.parent. 

Please see this commit  https://github.com/madington/parallax/commit/29dcb2271d67d2c519b325111f33ce26f84c46cb

**Comment by RRorg** [comment]
This violates origin restrictions and will not work.
