### ISSUE TITLE
Range limit X/Y.

### ISSUE THREAD

**Issue by kitsunde** [wagerfield/parallax#87]
I've used parallax in a rather complex project with full page transitions and multiple scenes and run into a few cases that have been difficult to deal with. I'm submitting my issues for your consideration.

Use case: I had one scene which was split down the middle with the right side black and the left an image. We were doing split screen transitions. It didn't make sense on these pages to shift the right side an equal distance as the left which had a background.

Being able to optionally pass an array into limit would be nice, like:

```
parallax.limit([-100, 0], false);
```

Though it's conceivable that one would want to limit a single element (in my case only the background).

**Comment by RRorg** [comment]
I don't really see a use case for this that couldn't be solved by offsetting the scene container. If you still have need for this and maybe even have an example to show, feel free to reopen the issue!

**Comment by avdeev** [comment]
I've done something like this in #267, but for each layer
