### ISSUE TITLE
Allow me to destroy and garbage collect the parallax object.

### ISSUE THREAD

**Issue by kitsunde** [wagerfield/parallax#88]
I ran into an issue where dynamically adding adding layers and updating the parallax.js settings for a new scene caused parallax.js to freak out (it was bobbing up and down). So naturally I wanted to stop the current parallax instance and create a new one for the scene but lacked a reliable way of destroying the object.

I resorted to this:

``` javascript
parallax.disable();
parallax = parallax.layers = parallax.element = undefined;
$("#scene").find(".layer").css("transform", "translate3d(0px, 0px, 0px)");
```

Adding on. I think another reason why I needed to destroy the parallax object is that it had already gone through the initial animation towards the mouse, so if I disabled it and re-enabled later on a different page it would "jerk" towards the mouse in a manner different from the initial friction.

**Comment by RRorg** [comment]
Keeping this open, being able to destroy the Parallax instance seems like it'd be good style. But no promises :)

**Comment by xmon** [comment]
I've diferents screens in the same page, I create a new parallax on each view, but when I leave the view, I have to keep the parallax, instead of being able to destroy it for a better performance, since it is not being seen.

I think it is a very good idea to implement this improvement in the plugin.

**Comment by mouhannad-sh** [comment]
Using parallax in one view only in a single page application, implementing this improvement is a great idea

**Comment by kstalega** [comment]
I also think that this very useful feature. I have slider with parallax and it will be great to have ability to destroy other slides parallax objects, especially on mobile.

**Comment by justrealmilk** [comment]
Please, God.

**Comment by RRorg** [comment]
I see this is something you're all very passionate about. I'll see that I get it done 😁

**Comment by RRorg** [comment]
Added in the latest release! <3
