### ISSUE TITLE
Custom selector for the layer

### ISSUE THREAD

**Issue by kitsunde** [wagerfield/parallax#89]
I was doing full page transitions and had multiple scenes. They all had to exist within the same element because I needed to keep all the foregrounds and backgrounds on the same layer and so couldn't wrap my scenes within individual base scene elements.

Being able to specify the layer selector would allow me to keep one Parallax object for each scene while not animating hidden scenes. Like:

``` javascript
var parallax = new Parallax(scene, {layerSelector: ".scene2layer"});
```

**Comment by totty90** [comment]
+1

**Comment by RRorg** [comment]
Is this still a problem? If so, please re-open this issue, and provide a project example.
