### ISSUE TITLE
Body duplicated

### ISSUE THREAD

**Issue by KuneStudio** [wagerfield/parallax#91]
Hi,
I can't explain why, but it looks like my body is duplicated when I use parallax.js on this page : http://kaarton.com/cine/event-category/cine-minots/

If anyone has an idea ...

Thanks a lot !

Regards

**Comment by panych** [comment]
:+1: for this issue.

**Comment by of6** [comment]
:+1:

**Comment by LazicDavid** [comment]
Confirmed both the problem and the solution. Body duplicate isn't present if parallaxJS is being loaded inside of body tag.

**Comment by drewbaker** [comment]
I just ran into this too

**Comment by RRorg** [comment]
this has been fixed by @aligo in #f00065b - thank you! :)
