### ISSUE TITLE
Cannot click on links in layers in Firefox 30+

### ISSUE THREAD

**Issue by adamkudrna** [wagerfield/parallax#93]
If there are any links in layers, they cannot be clicked on in Firefox 30+ (“they do not receive click event” is probably more technically correct). This can be fixed with overriding the `backface-visibility` inline style from `hidden` to `visible`.

Is there any reason why the `backface-visibility` property is used?

**Comment by ralleal** [comment]
Does anyone have a better solution to this problem? I want to handle mouseover/clicks in some elements in the scene that are overlapped with other layers, but I don't know if the 'pointer-events' solution is the best and more cross-browser. Thanks.

**Comment by RRorg** [comment]
Can't reproduce that problem in current Firefox versions. Please re-open that issue should it happen again :)

**Comment by Splendorr** [comment]
@RRorg I'm encountering a bug like this, I think! I have a site with 3 layers that works fine in Chrome and Safari, but nothing is clickable in Firefox. I tried rearranging the layers a bunch of different ways, but can't get them to work. Setting backface-visibility or pointer-events haven't made a difference in Firefox. I can't share the link publicly, but if you want to take a look, please send me a DM.

**Comment by RRorg** [comment]
@Splendorr please either create a trimmed-down public version (preferred), or simply email me the faulty project's link (not a problem either)
