### ISSUE TITLE
Commonjs Compatibility

### ISSUE THREAD

**Issue by jescalan** [wagerfield/parallax#95]
Hi!

Just wondering if you would be ok with making this script commonjs compatible so it could be installed with npm and used with browserify or one of the other many commonjs loaders. It should be pretty simple to make this upgrade using a UMD wrapper ([gulp-wrap-umd](https://www.npmjs.org/package/gulp-wrap-umd) is great for this, since you already use gulp). As an extra bonus, this would also make it work smoothly with requirejs and other AMD environments.

If you are cool with this I'd be happy to submit a pull request implementing it.

**Comment by joelcdoyle** [comment]
I have solved this by using browserify and the jquery version of parallax:

In package.json
```json
"browser": {
    "parallax": "./path/to/parallax/js/jquery.parallax.js"
  },
```
My main JS file (it's important to not even require it until the document is ready:
```js
window.$ = require('jquery');
$('document').ready(function () {
  var parallax = require('parallax');
  $('#parallax-scene').parallax();
});
```

**Comment by RRorg** [comment]
That's definitely on the roadmap for v3!

**Comment by RRorg** [comment]
hey you fine people, please check this thread and leave feedback if you can:
#171
